/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window (gtkTermPref* pref);
GtkWidget* create_window_about (void);
GtkWidget* create_terminal (GtkWidget *notebook, GtkWidget *window, gtkTermPref *pref);
