/* ANSI-C code produced by gperf version 3.0.2 */
/* Command-line: gperf -a -L ANSI-C -E -C -c -o -t --key-positions='*' -NfindProp -Hhash_prop -Wwordlist_prop -D -s 2 CSSPropertyNames.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "CSSPropertyNames.gperf"

/* This file is automatically generated from CSSPropertyNames.in by makeprop, do not edit */
#include "CSSPropertyNames.h"
#line 5 "CSSPropertyNames.gperf"
struct props {
    const char* name;
    int id;
};
/* maximum key range = 1471, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_prop (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474,    0, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474,    0,    0,   70,
         0,    5,  330,   15,  290,    0,    0,    0,   50,    0,
         0,    0,    0,    0,    0,   30,    0,  120,  120,    5,
       260,  330,  380, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474, 1474,
      1474, 1474, 1474, 1474, 1474, 1474
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[42]];
      /*FALLTHROUGH*/
      case 42:
        hval += asso_values[(unsigned char)str[41]];
      /*FALLTHROUGH*/
      case 41:
        hval += asso_values[(unsigned char)str[40]];
      /*FALLTHROUGH*/
      case 40:
        hval += asso_values[(unsigned char)str[39]];
      /*FALLTHROUGH*/
      case 39:
        hval += asso_values[(unsigned char)str[38]];
      /*FALLTHROUGH*/
      case 38:
        hval += asso_values[(unsigned char)str[37]];
      /*FALLTHROUGH*/
      case 37:
        hval += asso_values[(unsigned char)str[36]];
      /*FALLTHROUGH*/
      case 36:
        hval += asso_values[(unsigned char)str[35]];
      /*FALLTHROUGH*/
      case 35:
        hval += asso_values[(unsigned char)str[34]];
      /*FALLTHROUGH*/
      case 34:
        hval += asso_values[(unsigned char)str[33]];
      /*FALLTHROUGH*/
      case 33:
        hval += asso_values[(unsigned char)str[32]];
      /*FALLTHROUGH*/
      case 32:
        hval += asso_values[(unsigned char)str[31]];
      /*FALLTHROUGH*/
      case 31:
        hval += asso_values[(unsigned char)str[30]];
      /*FALLTHROUGH*/
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct props *
findProp (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 229,
      MIN_WORD_LENGTH = 3,
      MAX_WORD_LENGTH = 43,
      MIN_HASH_VALUE = 3,
      MAX_HASH_VALUE = 1473
    };

  static const struct props wordlist_prop[] =
    {
#line 125 "CSSPropertyNames.gperf"
      {"top", CSSPropertyTop},
#line 40 "CSSPropertyNames.gperf"
      {"bottom", CSSPropertyBottom},
#line 18 "CSSPropertyNames.gperf"
      {"border", CSSPropertyBorder},
#line 35 "CSSPropertyNames.gperf"
      {"border-top", CSSPropertyBorderTop},
#line 19 "CSSPropertyNames.gperf"
      {"border-bottom", CSSPropertyBorderBottom},
#line 135 "CSSPropertyNames.gperf"
      {"word-wrap", CSSPropertyWordWrap},
#line 133 "CSSPropertyNames.gperf"
      {"word-break", CSSPropertyWordBreak},
#line 68 "CSSPropertyNames.gperf"
      {"margin", CSSPropertyMargin},
#line 87 "CSSPropertyNames.gperf"
      {"padding", CSSPropertyPadding},
#line 92 "CSSPropertyNames.gperf"
      {"page", CSSPropertyPage},
#line 72 "CSSPropertyNames.gperf"
      {"margin-top", CSSPropertyMarginTop},
#line 91 "CSSPropertyNames.gperf"
      {"padding-top", CSSPropertyPaddingTop},
#line 138 "CSSPropertyNames.gperf"
      {"-webkit-animation", CSSPropertyWebkitAnimation},
#line 69 "CSSPropertyNames.gperf"
      {"margin-bottom", CSSPropertyMarginBottom},
#line 88 "CSSPropertyNames.gperf"
      {"padding-bottom", CSSPropertyPaddingBottom},
#line 143 "CSSPropertyNames.gperf"
      {"-webkit-animation-name", CSSPropertyWebkitAnimationName},
#line 97 "CSSPropertyNames.gperf"
      {"position", CSSPropertyPosition},
#line 151 "CSSPropertyNames.gperf"
      {"-webkit-binding", CSSPropertyWebkitBinding},
#line 131 "CSSPropertyNames.gperf"
      {"widows", CSSPropertyWidows},
#line 197 "CSSPropertyNames.gperf"
      {"-webkit-mask", CSSPropertyWebkitMask},
#line 156 "CSSPropertyNames.gperf"
      {"-webkit-border-image", CSSPropertyWebkitBorderImage},
#line 230 "CSSPropertyNames.gperf"
      {"-webkit-transition", CSSPropertyWebkitTransition},
#line 210 "CSSPropertyNames.gperf"
      {"-webkit-nbsp-mode", CSSPropertyWebkitNbspMode},
#line 207 "CSSPropertyNames.gperf"
      {"-webkit-mask-repeat", CSSPropertyWebkitMaskRepeat},
#line 203 "CSSPropertyNames.gperf"
      {"-webkit-mask-origin", CSSPropertyWebkitMaskOrigin},
#line 189 "CSSPropertyNames.gperf"
      {"-webkit-margin-start", CSSPropertyWebkitMarginStart},
#line 211 "CSSPropertyNames.gperf"
      {"-webkit-padding-start", CSSPropertyWebkitPaddingStart},
#line 95 "CSSPropertyNames.gperf"
      {"page-break-inside", CSSPropertyPageBreakInside},
#line 202 "CSSPropertyNames.gperf"
      {"-webkit-mask-image", CSSPropertyWebkitMaskImage},
#line 45 "CSSPropertyNames.gperf"
      {"content", CSSPropertyContent},
#line 49 "CSSPropertyNames.gperf"
      {"direction", CSSPropertyDirection},
#line 185 "CSSPropertyNames.gperf"
      {"-webkit-line-break", CSSPropertyWebkitLineBreak},
#line 204 "CSSPropertyNames.gperf"
      {"-webkit-mask-position", CSSPropertyWebkitMaskPosition},
#line 216 "CSSPropertyNames.gperf"
      {"-webkit-rtl-ordering", CSSPropertyWebkitRtlOrdering},
#line 102 "CSSPropertyNames.gperf"
      {"src", CSSPropertySrc},
#line 145 "CSSPropertyNames.gperf"
      {"-webkit-appearance", CSSPropertyWebkitAppearance},
#line 140 "CSSPropertyNames.gperf"
      {"-webkit-animation-direction", CSSPropertyWebkitAnimationDirection},
#line 41 "CSSPropertyNames.gperf"
      {"caption-side", CSSPropertyCaptionSide},
#line 43 "CSSPropertyNames.gperf"
      {"clip", CSSPropertyClip},
#line 44 "CSSPropertyNames.gperf"
      {"color", CSSPropertyColor},
#line 42 "CSSPropertyNames.gperf"
      {"clear", CSSPropertyClear},
#line 134 "CSSPropertyNames.gperf"
      {"word-spacing", CSSPropertyWordSpacing},
#line 33 "CSSPropertyNames.gperf"
      {"border-spacing", CSSPropertyBorderSpacing},
#line 24 "CSSPropertyNames.gperf"
      {"border-color", CSSPropertyBorderColor},
#line 36 "CSSPropertyNames.gperf"
      {"border-top-color", CSSPropertyBorderTopColor},
#line 20 "CSSPropertyNames.gperf"
      {"border-bottom-color", CSSPropertyBorderBottomColor},
#line 191 "CSSPropertyNames.gperf"
      {"-webkit-marquee", CSSPropertyWebkitMarquee},
#line 141 "CSSPropertyNames.gperf"
      {"-webkit-animation-duration", CSSPropertyWebkitAnimationDuration},
#line 98 "CSSPropertyNames.gperf"
      {"quotes", CSSPropertyQuotes},
#line 201 "CSSPropertyNames.gperf"
      {"-webkit-mask-composite", CSSPropertyWebkitMaskComposite},
#line 194 "CSSPropertyNames.gperf"
      {"-webkit-marquee-repetition", CSSPropertyWebkitMarqueeRepetition},
#line 200 "CSSPropertyNames.gperf"
      {"-webkit-mask-clip", CSSPropertyWebkitMaskClip},
#line 96 "CSSPropertyNames.gperf"
      {"pointer-events", CSSPropertyPointerEvents},
#line 79 "CSSPropertyNames.gperf"
      {"outline", CSSPropertyOutline},
#line 157 "CSSPropertyNames.gperf"
      {"-webkit-border-radius", CSSPropertyWebkitBorderRadius},
#line 232 "CSSPropertyNames.gperf"
      {"-webkit-transition-duration", CSSPropertyWebkitTransitionDuration},
#line 62 "CSSPropertyNames.gperf"
      {"letter-spacing", CSSPropertyLetterSpacing},
#line 235 "CSSPropertyNames.gperf"
      {"-webkit-user-drag", CSSPropertyWebkitUserDrag},
#line 195 "CSSPropertyNames.gperf"
      {"-webkit-marquee-speed", CSSPropertyWebkitMarqueeSpeed},
#line 186 "CSSPropertyNames.gperf"
      {"-webkit-line-clamp", CSSPropertyWebkitLineClamp},
#line 126 "CSSPropertyNames.gperf"
      {"unicode-bidi", CSSPropertyUnicodeBidi},
#line 10 "CSSPropertyNames.gperf"
      {"background", CSSPropertyBackground},
#line 23 "CSSPropertyNames.gperf"
      {"border-collapse", CSSPropertyBorderCollapse},
#line 48 "CSSPropertyNames.gperf"
      {"cursor", CSSPropertyCursor},
#line 127 "CSSPropertyNames.gperf"
      {"unicode-range", CSSPropertyUnicodeRange},
#line 17 "CSSPropertyNames.gperf"
      {"background-repeat", CSSPropertyBackgroundRepeat},
#line 142 "CSSPropertyNames.gperf"
      {"-webkit-animation-iteration-count", CSSPropertyWebkitAnimationIterationCount},
#line 192 "CSSPropertyNames.gperf"
      {"-webkit-marquee-direction", CSSPropertyWebkitMarqueeDirection},
#line 13 "CSSPropertyNames.gperf"
      {"background-image", CSSPropertyBackgroundImage},
#line 193 "CSSPropertyNames.gperf"
      {"-webkit-marquee-increment", CSSPropertyWebkitMarqueeIncrement},
#line 47 "CSSPropertyNames.gperf"
      {"counter-reset", CSSPropertyCounterReset},
#line 188 "CSSPropertyNames.gperf"
      {"-webkit-margin-collapse", CSSPropertyWebkitMarginCollapse},
#line 14 "CSSPropertyNames.gperf"
      {"background-position", CSSPropertyBackgroundPosition},
#line 149 "CSSPropertyNames.gperf"
      {"-webkit-background-origin", CSSPropertyWebkitBackgroundOrigin},
#line 190 "CSSPropertyNames.gperf"
      {"-webkit-margin-top-collapse", CSSPropertyWebkitMarginTopCollapse},
#line 187 "CSSPropertyNames.gperf"
      {"-webkit-margin-bottom-collapse", CSSPropertyWebkitMarginBottomCollapse},
#line 212 "CSSPropertyNames.gperf"
      {"-webkit-perspective", CSSPropertyWebkitPerspective},
#line 106 "CSSPropertyNames.gperf"
      {"text-indent", CSSPropertyTextIndent},
#line 176 "CSSPropertyNames.gperf"
      {"-webkit-column-gap", CSSPropertyWebkitColumnGap},
#line 213 "CSSPropertyNames.gperf"
      {"-webkit-perspective-origin", CSSPropertyWebkitPerspectiveOrigin},
#line 46 "CSSPropertyNames.gperf"
      {"counter-increment", CSSPropertyCounterIncrement},
#line 167 "CSSPropertyNames.gperf"
      {"-webkit-box-orient", CSSPropertyWebkitBoxOrient},
#line 182 "CSSPropertyNames.gperf"
      {"-webkit-columns", CSSPropertyWebkitColumns},
#line 132 "CSSPropertyNames.gperf"
      {"width", CSSPropertyWidth},
#line 76 "CSSPropertyNames.gperf"
      {"min-width", CSSPropertyMinWidth},
#line 80 "CSSPropertyNames.gperf"
      {"outline-color", CSSPropertyOutlineColor},
#line 100 "CSSPropertyNames.gperf"
      {"right", CSSPropertyRight},
#line 39 "CSSPropertyNames.gperf"
      {"border-width", CSSPropertyBorderWidth},
#line 38 "CSSPropertyNames.gperf"
      {"border-top-width", CSSPropertyBorderTopWidth},
#line 174 "CSSPropertyNames.gperf"
      {"-webkit-column-break-inside", CSSPropertyWebkitColumnBreakInside},
#line 22 "CSSPropertyNames.gperf"
      {"border-bottom-width", CSSPropertyBorderBottomWidth},
#line 29 "CSSPropertyNames.gperf"
      {"border-right", CSSPropertyBorderRight},
#line 128 "CSSPropertyNames.gperf"
      {"vertical-align", CSSPropertyVerticalAlign},
#line 78 "CSSPropertyNames.gperf"
      {"orphans", CSSPropertyOrphans},
#line 221 "CSSPropertyNames.gperf"
      {"-webkit-text-stroke", CSSPropertyWebkitTextStroke},
#line 71 "CSSPropertyNames.gperf"
      {"margin-right", CSSPropertyMarginRight},
#line 90 "CSSPropertyNames.gperf"
      {"padding-right", CSSPropertyPaddingRight},
#line 53 "CSSPropertyNames.gperf"
      {"font", CSSPropertyFont},
#line 104 "CSSPropertyNames.gperf"
      {"text-align", CSSPropertyTextAlign},
#line 12 "CSSPropertyNames.gperf"
      {"background-color", CSSPropertyBackgroundColor},
#line 199 "CSSPropertyNames.gperf"
      {"-webkit-mask-box-image", CSSPropertyWebkitMaskBoxImage},
#line 237 "CSSPropertyNames.gperf"
      {"-webkit-user-select", CSSPropertyWebkitUserSelect},
#line 148 "CSSPropertyNames.gperf"
      {"-webkit-background-composite", CSSPropertyWebkitBackgroundComposite},
#line 161 "CSSPropertyNames.gperf"
      {"-webkit-box-align", CSSPropertyWebkitBoxAlign},
#line 205 "CSSPropertyNames.gperf"
      {"-webkit-mask-position-x", CSSPropertyWebkitMaskPositionX},
#line 105 "CSSPropertyNames.gperf"
      {"text-decoration", CSSPropertyTextDecoration},
#line 168 "CSSPropertyNames.gperf"
      {"-webkit-box-pack", CSSPropertyWebkitBoxPack},
#line 147 "CSSPropertyNames.gperf"
      {"-webkit-background-clip", CSSPropertyWebkitBackgroundClip},
#line 154 "CSSPropertyNames.gperf"
      {"-webkit-border-fit", CSSPropertyWebkitBorderFit},
#line 162 "CSSPropertyNames.gperf"
      {"-webkit-box-direction", CSSPropertyWebkitBoxDirection},
#line 165 "CSSPropertyNames.gperf"
      {"-webkit-box-lines", CSSPropertyWebkitBoxLines},
#line 93 "CSSPropertyNames.gperf"
      {"page-break-after", CSSPropertyPageBreakAfter},
#line 94 "CSSPropertyNames.gperf"
      {"page-break-before", CSSPropertyPageBreakBefore},
#line 137 "CSSPropertyNames.gperf"
      {"zoom", CSSPropertyZoom},
#line 52 "CSSPropertyNames.gperf"
      {"float", CSSPropertyFloat},
#line 224 "CSSPropertyNames.gperf"
      {"-webkit-transform", CSSPropertyWebkitTransform},
#line 61 "CSSPropertyNames.gperf"
      {"left", CSSPropertyLeft},
#line 25 "CSSPropertyNames.gperf"
      {"border-left", CSSPropertyBorderLeft},
#line 233 "CSSPropertyNames.gperf"
      {"-webkit-transition-property", CSSPropertyWebkitTransitionProperty},
#line 160 "CSSPropertyNames.gperf"
      {"-webkit-border-vertical-spacing", CSSPropertyWebkitBorderVerticalSpacing},
#line 77 "CSSPropertyNames.gperf"
      {"opacity", CSSPropertyOpacity},
#line 225 "CSSPropertyNames.gperf"
      {"-webkit-transform-origin", CSSPropertyWebkitTransformOrigin},
#line 70 "CSSPropertyNames.gperf"
      {"margin-left", CSSPropertyMarginLeft},
#line 89 "CSSPropertyNames.gperf"
      {"padding-left", CSSPropertyPaddingLeft},
#line 130 "CSSPropertyNames.gperf"
      {"white-space", CSSPropertyWhiteSpace},
#line 50 "CSSPropertyNames.gperf"
      {"display", CSSPropertyDisplay},
#line 139 "CSSPropertyNames.gperf"
      {"-webkit-animation-delay", CSSPropertyWebkitAnimationDelay},
#line 101 "CSSPropertyNames.gperf"
      {"size", CSSPropertySize},
#line 206 "CSSPropertyNames.gperf"
      {"-webkit-mask-position-y", CSSPropertyWebkitMaskPositionY},
#line 99 "CSSPropertyNames.gperf"
      {"resize", CSSPropertyResize},
#line 198 "CSSPropertyNames.gperf"
      {"-webkit-mask-attachment", CSSPropertyWebkitMaskAttachment},
#line 34 "CSSPropertyNames.gperf"
      {"border-style", CSSPropertyBorderStyle},
#line 37 "CSSPropertyNames.gperf"
      {"border-top-style", CSSPropertyBorderTopStyle},
#line 21 "CSSPropertyNames.gperf"
      {"border-bottom-style", CSSPropertyBorderBottomStyle},
#line 177 "CSSPropertyNames.gperf"
      {"-webkit-column-rule", CSSPropertyWebkitColumnRule},
#line 30 "CSSPropertyNames.gperf"
      {"border-right-color", CSSPropertyBorderRightColor},
#line 231 "CSSPropertyNames.gperf"
      {"-webkit-transition-delay", CSSPropertyWebkitTransitionDelay},
#line 222 "CSSPropertyNames.gperf"
      {"-webkit-text-stroke-color", CSSPropertyWebkitTextStrokeColor},
#line 113 "CSSPropertyNames.gperf"
      {"text-overline", CSSPropertyTextOverline},
#line 120 "CSSPropertyNames.gperf"
      {"text-underline", CSSPropertyTextUnderline},
#line 175 "CSSPropertyNames.gperf"
      {"-webkit-column-count", CSSPropertyWebkitColumnCount},
#line 58 "CSSPropertyNames.gperf"
      {"font-variant", CSSPropertyFontVariant},
#line 238 "CSSPropertyNames.gperf"
      {"-webkit-variable-declaration-block", CSSPropertyWebkitVariableDeclarationBlock},
#line 115 "CSSPropertyNames.gperf"
      {"text-overline-mode", CSSPropertyTextOverlineMode},
#line 122 "CSSPropertyNames.gperf"
      {"text-underline-mode", CSSPropertyTextUnderlineMode},
#line 208 "CSSPropertyNames.gperf"
      {"-webkit-mask-size", CSSPropertyWebkitMaskSize},
#line 166 "CSSPropertyNames.gperf"
      {"-webkit-box-ordinal-group", CSSPropertyWebkitBoxOrdinalGroup},
#line 83 "CSSPropertyNames.gperf"
      {"outline-width", CSSPropertyOutlineWidth},
#line 159 "CSSPropertyNames.gperf"
      {"-webkit-border-top-right-radius", CSSPropertyWebkitBorderTopRightRadius},
#line 153 "CSSPropertyNames.gperf"
      {"-webkit-border-bottom-right-radius", CSSPropertyWebkitBorderBottomRightRadius},
#line 64 "CSSPropertyNames.gperf"
      {"list-style", CSSPropertyListStyle},
#line 15 "CSSPropertyNames.gperf"
      {"background-position-x", CSSPropertyBackgroundPositionX},
#line 84 "CSSPropertyNames.gperf"
      {"overflow", CSSPropertyOverflow},
#line 26 "CSSPropertyNames.gperf"
      {"border-left-color", CSSPropertyBorderLeftColor},
#line 65 "CSSPropertyNames.gperf"
      {"list-style-image", CSSPropertyListStyleImage},
#line 129 "CSSPropertyNames.gperf"
      {"visibility", CSSPropertyVisibility},
#line 66 "CSSPropertyNames.gperf"
      {"list-style-position", CSSPropertyListStylePosition},
#line 214 "CSSPropertyNames.gperf"
      {"-webkit-perspective-origin-x", CSSPropertyWebkitPerspectiveOriginX},
#line 51 "CSSPropertyNames.gperf"
      {"empty-cells", CSSPropertyEmptyCells},
#line 74 "CSSPropertyNames.gperf"
      {"max-width", CSSPropertyMaxWidth},
#line 181 "CSSPropertyNames.gperf"
      {"-webkit-column-width", CSSPropertyWebkitColumnWidth},
#line 103 "CSSPropertyNames.gperf"
      {"table-layout", CSSPropertyTableLayout},
#line 178 "CSSPropertyNames.gperf"
      {"-webkit-column-rule-color", CSSPropertyWebkitColumnRuleColor},
#line 196 "CSSPropertyNames.gperf"
      {"-webkit-marquee-style", CSSPropertyWebkitMarqueeStyle},
#line 144 "CSSPropertyNames.gperf"
      {"-webkit-animation-timing-function", CSSPropertyWebkitAnimationTimingFunction},
#line 158 "CSSPropertyNames.gperf"
      {"-webkit-border-top-left-radius", CSSPropertyWebkitBorderTopLeftRadius},
#line 152 "CSSPropertyNames.gperf"
      {"-webkit-border-bottom-left-radius", CSSPropertyWebkitBorderBottomLeftRadius},
#line 114 "CSSPropertyNames.gperf"
      {"text-overline-color", CSSPropertyTextOverlineColor},
#line 121 "CSSPropertyNames.gperf"
      {"text-underline-color", CSSPropertyTextUnderlineColor},
#line 16 "CSSPropertyNames.gperf"
      {"background-position-y", CSSPropertyBackgroundPositionY},
#line 11 "CSSPropertyNames.gperf"
      {"background-attachment", CSSPropertyBackgroundAttachment},
#line 118 "CSSPropertyNames.gperf"
      {"text-shadow", CSSPropertyTextShadow},
#line 82 "CSSPropertyNames.gperf"
      {"outline-style", CSSPropertyOutlineStyle},
#line 60 "CSSPropertyNames.gperf"
      {"height", CSSPropertyHeight},
#line 234 "CSSPropertyNames.gperf"
      {"-webkit-transition-timing-function", CSSPropertyWebkitTransitionTimingFunction},
#line 75 "CSSPropertyNames.gperf"
      {"min-height", CSSPropertyMinHeight},
#line 170 "CSSPropertyNames.gperf"
      {"-webkit-box-shadow", CSSPropertyWebkitBoxShadow},
#line 172 "CSSPropertyNames.gperf"
      {"-webkit-column-break-after", CSSPropertyWebkitColumnBreakAfter},
#line 215 "CSSPropertyNames.gperf"
      {"-webkit-perspective-origin-y", CSSPropertyWebkitPerspectiveOriginY},
#line 173 "CSSPropertyNames.gperf"
      {"-webkit-column-break-before", CSSPropertyWebkitColumnBreakBefore},
#line 32 "CSSPropertyNames.gperf"
      {"border-right-width", CSSPropertyBorderRightWidth},
#line 223 "CSSPropertyNames.gperf"
      {"-webkit-text-stroke-width", CSSPropertyWebkitTextStrokeWidth},
#line 119 "CSSPropertyNames.gperf"
      {"text-transform", CSSPropertyTextTransform},
#line 136 "CSSPropertyNames.gperf"
      {"z-index", CSSPropertyZIndex},
#line 150 "CSSPropertyNames.gperf"
      {"-webkit-background-size", CSSPropertyWebkitBackgroundSize},
#line 59 "CSSPropertyNames.gperf"
      {"font-weight", CSSPropertyFontWeight},
#line 63 "CSSPropertyNames.gperf"
      {"line-height", CSSPropertyLineHeight},
#line 226 "CSSPropertyNames.gperf"
      {"-webkit-transform-origin-x", CSSPropertyWebkitTransformOriginX},
#line 28 "CSSPropertyNames.gperf"
      {"border-left-width", CSSPropertyBorderLeftWidth},
#line 171 "CSSPropertyNames.gperf"
      {"-webkit-box-sizing", CSSPropertyWebkitBoxSizing},
#line 56 "CSSPropertyNames.gperf"
      {"font-stretch", CSSPropertyFontStretch},
#line 227 "CSSPropertyNames.gperf"
      {"-webkit-transform-origin-y", CSSPropertyWebkitTransformOriginY},
#line 31 "CSSPropertyNames.gperf"
      {"border-right-style", CSSPropertyBorderRightStyle},
#line 180 "CSSPropertyNames.gperf"
      {"-webkit-column-rule-width", CSSPropertyWebkitColumnRuleWidth},
#line 169 "CSSPropertyNames.gperf"
      {"-webkit-box-reflect", CSSPropertyWebkitBoxReflect},
#line 55 "CSSPropertyNames.gperf"
      {"font-size", CSSPropertyFontSize},
#line 57 "CSSPropertyNames.gperf"
      {"font-style", CSSPropertyFontStyle},
#line 117 "CSSPropertyNames.gperf"
      {"text-overline-width", CSSPropertyTextOverlineWidth},
#line 124 "CSSPropertyNames.gperf"
      {"text-underline-width", CSSPropertyTextUnderlineWidth},
#line 85 "CSSPropertyNames.gperf"
      {"overflow-x", CSSPropertyOverflowX},
#line 112 "CSSPropertyNames.gperf"
      {"text-overflow", CSSPropertyTextOverflow},
#line 228 "CSSPropertyNames.gperf"
      {"-webkit-transform-origin-z", CSSPropertyWebkitTransformOriginZ},
#line 229 "CSSPropertyNames.gperf"
      {"-webkit-transform-style", CSSPropertyWebkitTransformStyle},
#line 27 "CSSPropertyNames.gperf"
      {"border-left-style", CSSPropertyBorderLeftStyle},
#line 183 "CSSPropertyNames.gperf"
      {"-webkit-font-size-delta", CSSPropertyWebkitFontSizeDelta},
#line 236 "CSSPropertyNames.gperf"
      {"-webkit-user-modify", CSSPropertyWebkitUserModify},
#line 67 "CSSPropertyNames.gperf"
      {"list-style-type", CSSPropertyListStyleType},
#line 218 "CSSPropertyNames.gperf"
      {"-webkit-text-fill-color", CSSPropertyWebkitTextFillColor},
#line 86 "CSSPropertyNames.gperf"
      {"overflow-y", CSSPropertyOverflowY},
#line 219 "CSSPropertyNames.gperf"
      {"-webkit-text-security", CSSPropertyWebkitTextSecurity},
#line 220 "CSSPropertyNames.gperf"
      {"-webkit-text-size-adjust", CSSPropertyWebkitTextSizeAdjust},
#line 179 "CSSPropertyNames.gperf"
      {"-webkit-column-rule-style", CSSPropertyWebkitColumnRuleStyle},
#line 209 "CSSPropertyNames.gperf"
      {"-webkit-match-nearest-mail-blockquote-color", CSSPropertyWebkitMatchNearestMailBlockquoteColor},
#line 73 "CSSPropertyNames.gperf"
      {"max-height", CSSPropertyMaxHeight},
#line 116 "CSSPropertyNames.gperf"
      {"text-overline-style", CSSPropertyTextOverlineStyle},
#line 123 "CSSPropertyNames.gperf"
      {"text-underline-style", CSSPropertyTextUnderlineStyle},
#line 155 "CSSPropertyNames.gperf"
      {"-webkit-border-horizontal-spacing", CSSPropertyWebkitBorderHorizontalSpacing},
#line 81 "CSSPropertyNames.gperf"
      {"outline-offset", CSSPropertyOutlineOffset},
#line 163 "CSSPropertyNames.gperf"
      {"-webkit-box-flex", CSSPropertyWebkitBoxFlex},
#line 184 "CSSPropertyNames.gperf"
      {"-webkit-highlight", CSSPropertyWebkitHighlight},
#line 146 "CSSPropertyNames.gperf"
      {"-webkit-backface-visibility", CSSPropertyWebkitBackfaceVisibility},
#line 54 "CSSPropertyNames.gperf"
      {"font-family", CSSPropertyFontFamily},
#line 107 "CSSPropertyNames.gperf"
      {"text-line-through", CSSPropertyTextLineThrough},
#line 109 "CSSPropertyNames.gperf"
      {"text-line-through-mode", CSSPropertyTextLineThroughMode},
#line 164 "CSSPropertyNames.gperf"
      {"-webkit-box-flex-group", CSSPropertyWebkitBoxFlexGroup},
#line 217 "CSSPropertyNames.gperf"
      {"-webkit-text-decorations-in-effect", CSSPropertyWebkitTextDecorationsInEffect},
#line 108 "CSSPropertyNames.gperf"
      {"text-line-through-color", CSSPropertyTextLineThroughColor},
#line 111 "CSSPropertyNames.gperf"
      {"text-line-through-width", CSSPropertyTextLineThroughWidth},
#line 110 "CSSPropertyNames.gperf"
      {"text-line-through-style", CSSPropertyTextLineThroughStyle}
    };

  static const short lookup[] =
    {
       -1,  -1,  -1,   0,  -1,  -1,   1,  -1,  -1,  -1,
       -1,   2,  -1,  -1,  -1,   3,  -1,  -1,   4,   5,
        6,   7,   8,  -1,   9,  10,  11,  12,  13,  14,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  15,  16,  -1,
       17,  -1,  -1,  -1,  -1,  -1,  18,  -1,  -1,  -1,
       -1,  -1,  19,  -1,  -1,  20,  -1,  -1,  21,  -1,
       -1,  -1,  22,  -1,  -1,  -1,  -1,  -1,  -1,  23,
       -1,  -1,  -1,  -1,  24,  25,  26,  27,  28,  -1,
       -1,  -1,  29,  -1,  30,  -1,  -1,  -1,  31,  -1,
       -1,  32,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       33,  -1,  -1,  34,  -1,  -1,  -1,  -1,  35,  -1,
       -1,  -1,  36,  -1,  -1,  -1,  -1,  37,  -1,  -1,
       -1,  -1,  -1,  -1,  38,  39,  -1,  -1,  -1,  -1,
       40,  -1,  41,  -1,  42,  -1,  -1,  43,  -1,  -1,
       -1,  44,  -1,  -1,  45,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  46,  47,  -1,  -1,  -1,
       -1,  48,  -1,  -1,  -1,  -1,  -1,  49,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  50,  51,  -1,  52,
       -1,  -1,  53,  -1,  -1,  -1,  54,  55,  -1,  56,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  57,  -1,  -1,
       -1,  58,  -1,  59,  -1,  -1,  -1,  60,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  61,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  62,  63,  -1,  64,  -1,
       -1,  -1,  65,  -1,  -1,  -1,  -1,  -1,  66,  -1,
       67,  68,  -1,  -1,  -1,  69,  -1,  -1,  70,  -1,
       -1,  -1,  -1,  71,  72,  73,  -1,  74,  -1,  -1,
       75,  -1,  -1,  -1,  76,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  77,  -1,  78,  -1,  -1,  79,  -1,  -1,  -1,
       -1,  -1,  80,  81,  -1,  82,  -1,  -1,  -1,  -1,
       83,  -1,  -1,  -1,  84,  -1,  -1,  -1,  85,  -1,
       86,  -1,  87,  -1,  -1,  -1,  88,  89,  -1,  90,
       -1,  -1,  91,  -1,  92,  -1,  -1,  93,  -1,  94,
       -1,  -1,  95,  96,  97,  -1,  -1,  -1,  -1,  -1,
       98,  99, 100,  -1, 101,  -1,  -1,  -1, 102,  -1,
       -1,  -1, 103, 104,  -1, 105, 106,  -1, 107,  -1,
       -1,  -1,  -1, 108,  -1,  -1, 109,  -1,  -1,  -1,
       -1,  -1, 110,  -1,  -1,  -1, 111,  -1,  -1,  -1,
       -1,  -1, 112,  -1, 113, 114,  -1, 115,  -1, 116,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 117, 118,  -1,  -1,  -1, 119, 120,  -1, 121,
       -1, 122, 123,  -1,  -1,  -1, 124, 125, 126, 127,
       -1,  -1,  -1, 128,  -1,  -1, 129,  -1, 130,  -1,
       -1,  -1, 131,  -1,  -1,  -1, 132,  -1,  -1, 133,
       -1,  -1,  -1,  -1, 134,  -1,  -1,  -1, 135, 136,
       -1,  -1,  -1,  -1,  -1, 137,  -1,  -1, 138, 139,
      140,  -1, 141,  -1, 142,  -1,  -1,  -1, 143, 144,
       -1,  -1, 145,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      146,  -1,  -1, 147,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 148,  -1,  -1, 149, 150,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 151,  -1, 152,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 153,  -1,  -1,
       -1, 154,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      155,  -1,  -1,  -1, 156,  -1,  -1,  -1, 157,  -1,
       -1, 158,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 159, 160,  -1, 161,  -1,  -1,
      162,  -1,  -1,  -1,  -1,  -1, 163,  -1, 164,  -1,
      165,  -1,  -1, 166, 167, 168, 169,  -1,  -1,  -1,
       -1, 170,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 171,  -1, 172,  -1,  -1, 173,  -1,  -1, 174,
      175,  -1,  -1, 176,  -1,  -1, 177,  -1, 178,  -1,
       -1,  -1, 179, 180,  -1,  -1,  -1,  -1,  -1,  -1,
      181,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 182,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 183, 184,  -1,  -1, 185,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 186,  -1,  -1,  -1,
       -1, 187,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 189,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 190,  -1,  -1,
       -1, 191,  -1, 192,  -1, 193,  -1,  -1,  -1, 194,
       -1,  -1,  -1,  -1, 195, 196,  -1,  -1,  -1, 197,
      198,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      199,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 200,  -1,
       -1, 201,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 202,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 203,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 204,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 205, 206,  -1,  -1, 207,  -1,
      208, 209,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 210, 211,  -1,  -1, 212,  -1,
      213,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 214,
      215,  -1,  -1, 216, 217,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 218,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 219,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 220,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 221, 222,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 223,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 224,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 225,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 226,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 227,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 228
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_prop (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_prop[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &wordlist_prop[index];
            }
        }
    }
  return 0;
}
#line 239 "CSSPropertyNames.gperf"

static const char * const propertyNameStrings[229] = {
"background",
"background-attachment",
"background-color",
"background-image",
"background-position",
"background-position-x",
"background-position-y",
"background-repeat",
"border",
"border-bottom",
"border-bottom-color",
"border-bottom-style",
"border-bottom-width",
"border-collapse",
"border-color",
"border-left",
"border-left-color",
"border-left-style",
"border-left-width",
"border-right",
"border-right-color",
"border-right-style",
"border-right-width",
"border-spacing",
"border-style",
"border-top",
"border-top-color",
"border-top-style",
"border-top-width",
"border-width",
"bottom",
"caption-side",
"clear",
"clip",
"color",
"content",
"counter-increment",
"counter-reset",
"cursor",
"direction",
"display",
"empty-cells",
"float",
"font",
"font-family",
"font-size",
"font-stretch",
"font-style",
"font-variant",
"font-weight",
"height",
"left",
"letter-spacing",
"line-height",
"list-style",
"list-style-image",
"list-style-position",
"list-style-type",
"margin",
"margin-bottom",
"margin-left",
"margin-right",
"margin-top",
"max-height",
"max-width",
"min-height",
"min-width",
"opacity",
"orphans",
"outline",
"outline-color",
"outline-offset",
"outline-style",
"outline-width",
"overflow",
"overflow-x",
"overflow-y",
"padding",
"padding-bottom",
"padding-left",
"padding-right",
"padding-top",
"page",
"page-break-after",
"page-break-before",
"page-break-inside",
"pointer-events",
"position",
"quotes",
"resize",
"right",
"size",
"src",
"table-layout",
"text-align",
"text-decoration",
"text-indent",
"text-line-through",
"text-line-through-color",
"text-line-through-mode",
"text-line-through-style",
"text-line-through-width",
"text-overflow",
"text-overline",
"text-overline-color",
"text-overline-mode",
"text-overline-style",
"text-overline-width",
"text-shadow",
"text-transform",
"text-underline",
"text-underline-color",
"text-underline-mode",
"text-underline-style",
"text-underline-width",
"top",
"unicode-bidi",
"unicode-range",
"vertical-align",
"visibility",
"white-space",
"widows",
"width",
"word-break",
"word-spacing",
"word-wrap",
"z-index",
"zoom",
"-webkit-animation",
"-webkit-animation-delay",
"-webkit-animation-direction",
"-webkit-animation-duration",
"-webkit-animation-iteration-count",
"-webkit-animation-name",
"-webkit-animation-timing-function",
"-webkit-appearance",
"-webkit-backface-visibility",
"-webkit-background-clip",
"-webkit-background-composite",
"-webkit-background-origin",
"-webkit-background-size",
"-webkit-binding",
"-webkit-border-bottom-left-radius",
"-webkit-border-bottom-right-radius",
"-webkit-border-fit",
"-webkit-border-horizontal-spacing",
"-webkit-border-image",
"-webkit-border-radius",
"-webkit-border-top-left-radius",
"-webkit-border-top-right-radius",
"-webkit-border-vertical-spacing",
"-webkit-box-align",
"-webkit-box-direction",
"-webkit-box-flex",
"-webkit-box-flex-group",
"-webkit-box-lines",
"-webkit-box-ordinal-group",
"-webkit-box-orient",
"-webkit-box-pack",
"-webkit-box-reflect",
"-webkit-box-shadow",
"-webkit-box-sizing",
"-webkit-column-break-after",
"-webkit-column-break-before",
"-webkit-column-break-inside",
"-webkit-column-count",
"-webkit-column-gap",
"-webkit-column-rule",
"-webkit-column-rule-color",
"-webkit-column-rule-style",
"-webkit-column-rule-width",
"-webkit-column-width",
"-webkit-columns",
"-webkit-font-size-delta",
"-webkit-highlight",
"-webkit-line-break",
"-webkit-line-clamp",
"-webkit-margin-bottom-collapse",
"-webkit-margin-collapse",
"-webkit-margin-start",
"-webkit-margin-top-collapse",
"-webkit-marquee",
"-webkit-marquee-direction",
"-webkit-marquee-increment",
"-webkit-marquee-repetition",
"-webkit-marquee-speed",
"-webkit-marquee-style",
"-webkit-mask",
"-webkit-mask-attachment",
"-webkit-mask-box-image",
"-webkit-mask-clip",
"-webkit-mask-composite",
"-webkit-mask-image",
"-webkit-mask-origin",
"-webkit-mask-position",
"-webkit-mask-position-x",
"-webkit-mask-position-y",
"-webkit-mask-repeat",
"-webkit-mask-size",
"-webkit-match-nearest-mail-blockquote-color",
"-webkit-nbsp-mode",
"-webkit-padding-start",
"-webkit-perspective",
"-webkit-perspective-origin",
"-webkit-perspective-origin-x",
"-webkit-perspective-origin-y",
"-webkit-rtl-ordering",
"-webkit-text-decorations-in-effect",
"-webkit-text-fill-color",
"-webkit-text-security",
"-webkit-text-size-adjust",
"-webkit-text-stroke",
"-webkit-text-stroke-color",
"-webkit-text-stroke-width",
"-webkit-transform",
"-webkit-transform-origin",
"-webkit-transform-origin-x",
"-webkit-transform-origin-y",
"-webkit-transform-origin-z",
"-webkit-transform-style",
"-webkit-transition",
"-webkit-transition-delay",
"-webkit-transition-duration",
"-webkit-transition-property",
"-webkit-transition-timing-function",
"-webkit-user-drag",
"-webkit-user-modify",
"-webkit-user-select",
"-webkit-variable-declaration-block",
};
const char* getPropertyName(CSSPropertyID id)
{
    if (id < firstCSSProperty)
        return 0;
    int index = id - firstCSSProperty;
    if (index >= numCSSProperties)
        return 0;
    return propertyNameStrings[index];
}
