/* ANSI-C code produced by gperf version 3.0.2 */
/* Command-line: gperf -L ANSI-C -E -C -n -o -t --key-positions='*' -NfindValue -Hhash_val -Wwordlist_value -D CSSValueKeywords.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "CSSValueKeywords.gperf"

/* This file is automatically generated from CSSValueKeywords.in by makevalues, do not edit */

#include "CSSValueKeywords.h"
#line 6 "CSSValueKeywords.gperf"
struct css_value {
    const char* name;
    int id;
};
/* maximum key range = 2696, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_val (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701,  205,   87, 2701,   20,    5,
        95,    0,   75,   60,   55,   45,   25,   20, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701,  255,   65,  110,
       380,    0,   15,  331,    3,   15,    8,  320,   20,   30,
        10,   55,  155,  146,    5,  105,    0,   30,    3,   16,
       123,  146,   33, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701, 2701,
      2701, 2701, 2701, 2701, 2701, 2701, 2701
    };
  register int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]+1];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]+1];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct css_value *
findValue (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 376,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 30,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 2700
    };

  static const struct css_value wordlist_value[] =
    {
#line 87 "CSSValueKeywords.gperf"
      {"red", CSSValueRed},
#line 287 "CSSValueKeywords.gperf"
      {"end", CSSValueEnd},
#line 380 "CSSValueKeywords.gperf"
      {"reset", CSSValueReset},
#line 17 "CSSValueKeywords.gperf"
      {"ridge", CSSValueRidge},
#line 42 "CSSValueKeywords.gperf"
      {"300", CSSValue300},
#line 14 "CSSValueKeywords.gperf"
      {"hidden", CSSValueHidden},
#line 40 "CSSValueKeywords.gperf"
      {"100", CSSValue100},
#line 256 "CSSValueKeywords.gperf"
      {"hide", CSSValueHide},
#line 236 "CSSValueKeywords.gperf"
      {"rtl", CSSValueRtl},
#line 155 "CSSValueKeywords.gperf"
      {"right", CSSValueRight},
#line 15 "CSSValueKeywords.gperf"
      {"inset", CSSValueInset},
#line 257 "CSSValueKeywords.gperf"
      {"higher", CSSValueHigher},
#line 48 "CSSValueKeywords.gperf"
      {"900", CSSValue900},
#line 47 "CSSValueKeywords.gperf"
      {"800", CSSValue800},
#line 59 "CSSValueKeywords.gperf"
      {"wider", CSSValueWider},
#line 308 "CSSValueKeywords.gperf"
      {"element", CSSValueElement},
#line 90 "CSSValueKeywords.gperf"
      {"white", CSSValueWhite},
#line 39 "CSSValueKeywords.gperf"
      {"lighter", CSSValueLighter},
#line 81 "CSSValueKeywords.gperf"
      {"lime", CSSValueLime},
#line 258 "CSSValueKeywords.gperf"
      {"invert", CSSValueInvert},
#line 145 "CSSValueKeywords.gperf"
      {"middle", CSSValueMiddle},
#line 282 "CSSValueKeywords.gperf"
      {"thin", CSSValueThin},
#line 46 "CSSValueKeywords.gperf"
      {"700", CSSValue700},
#line 260 "CSSValueKeywords.gperf"
      {"level", CSSValueLevel},
#line 183 "CSSValueKeywords.gperf"
      {"inline", CSSValueInline},
#line 11 "CSSValueKeywords.gperf"
      {"inherit", CSSValueInherit},
#line 262 "CSSValueKeywords.gperf"
      {"loud", CSSValueLoud},
#line 45 "CSSValueKeywords.gperf"
      {"600", CSSValue600},
#line 44 "CSSValueKeywords.gperf"
      {"500", CSSValue500},
#line 25 "CSSValueKeywords.gperf"
      {"menu", CSSValueMenu},
#line 385 "CSSValueKeywords.gperf"
      {"fill", CSSValueFill},
#line 89 "CSSValueKeywords.gperf"
      {"teal", CSSValueTeal},
#line 52 "CSSValueKeywords.gperf"
      {"medium", CSSValueMedium},
#line 84 "CSSValueKeywords.gperf"
      {"olive", CSSValueOlive},
#line 43 "CSSValueKeywords.gperf"
      {"400", CSSValue400},
#line 77 "CSSValueKeywords.gperf"
      {"blue", CSSValueBlue},
#line 283 "CSSValueKeywords.gperf"
      {"underline", CSSValueUnderline},
#line 332 "CSSValueKeywords.gperf"
      {"listitem", CSSValueListitem},
#line 240 "CSSValueKeywords.gperf"
      {"visible", CSSValueVisible},
#line 18 "CSSValueKeywords.gperf"
      {"outset", CSSValueOutset},
#line 205 "CSSValueKeywords.gperf"
      {"move", CSSValueMove},
#line 276 "CSSValueKeywords.gperf"
      {"relative", CSSValueRelative},
#line 41 "CSSValueKeywords.gperf"
      {"200", CSSValue200},
#line 235 "CSSValueKeywords.gperf"
      {"ltr", CSSValueLtr},
#line 372 "CSSValueKeywords.gperf"
      {"flat", CSSValueFlat},
#line 303 "CSSValueKeywords.gperf"
      {"slide", CSSValueSlide},
#line 13 "CSSValueKeywords.gperf"
      {"none", CSSValueNone},
#line 288 "CSSValueKeywords.gperf"
      {"reverse", CSSValueReverse},
#line 37 "CSSValueKeywords.gperf"
      {"bold", CSSValueBold},
#line 38 "CSSValueKeywords.gperf"
      {"bolder", CSSValueBolder},
#line 120 "CSSValueKeywords.gperf"
      {"window", CSSValueWindow},
#line 249 "CSSValueKeywords.gperf"
      {"both", CSSValueBoth},
#line 207 "CSSValueKeywords.gperf"
      {"cell", CSSValueCell},
#line 88 "CSSValueKeywords.gperf"
      {"silver", CSSValueSilver},
#line 273 "CSSValueKeywords.gperf"
      {"pre", CSSValuePre},
#line 229 "CSSValueKeywords.gperf"
      {"text", CSSValueText},
#line 231 "CSSValueKeywords.gperf"
      {"help", CSSValueHelp},
#line 382 "CSSValueKeywords.gperf"
      {"visiblefill", CSSValueVisiblefill},
#line 298 "CSSValueKeywords.gperf"
      {"up", CSSValueUp},
#line 265 "CSSValueKeywords.gperf"
      {"mix", CSSValueMix},
#line 293 "CSSValueKeywords.gperf"
      {"single", CSSValueSingle},
#line 156 "CSSValueKeywords.gperf"
      {"center", CSSValueCenter},
#line 150 "CSSValueKeywords.gperf"
      {"top", CSSValueTop},
#line 186 "CSSValueKeywords.gperf"
      {"run-in", CSSValueRunIn},
#line 369 "CSSValueKeywords.gperf"
      {"lines", CSSValueLines},
#line 113 "CSSValueKeywords.gperf"
      {"menutext", CSSValueMenutext},
#line 131 "CSSValueKeywords.gperf"
      {"clear", CSSValueClear},
#line 263 "CSSValueKeywords.gperf"
      {"lower", CSSValueLower},
#line 328 "CSSValueKeywords.gperf"
      {"button", CSSValueButton},
#line 271 "CSSValueKeywords.gperf"
      {"overline", CSSValueOverline},
#line 343 "CSSValueKeywords.gperf"
      {"menulist", CSSValueMenulist},
#line 361 "CSSValueKeywords.gperf"
      {"border", CSSValueBorder},
#line 69 "CSSValueKeywords.gperf"
      {"serif", CSSValueSerif},
#line 175 "CSSValueKeywords.gperf"
      {"hebrew", CSSValueHebrew},
#line 32 "CSSValueKeywords.gperf"
      {"italic", CSSValueItalic},
#line 157 "CSSValueKeywords.gperf"
      {"justify", CSSValueJustify},
#line 146 "CSSValueKeywords.gperf"
      {"sub", CSSValueSub},
#line 51 "CSSValueKeywords.gperf"
      {"small", CSSValueSmall},
#line 57 "CSSValueKeywords.gperf"
      {"smaller", CSSValueSmaller},
#line 362 "CSSValueKeywords.gperf"
      {"content", CSSValueContent},
#line 71 "CSSValueKeywords.gperf"
      {"cursive", CSSValueCursive},
#line 151 "CSSValueKeywords.gperf"
      {"bottom", CSSValueBottom},
#line 246 "CSSValueKeywords.gperf"
      {"below", CSSValueBelow},
#line 374 "CSSValueKeywords.gperf"
      {"ease", CSSValueEase},
#line 286 "CSSValueKeywords.gperf"
      {"start", CSSValueStart},
#line 91 "CSSValueKeywords.gperf"
      {"yellow", CSSValueYellow},
#line 204 "CSSValueKeywords.gperf"
      {"pointer", CSSValuePointer},
#line 122 "CSSValueKeywords.gperf"
      {"windowtext", CSSValueWindowtext},
#line 141 "CSSValueKeywords.gperf"
      {"xor", CSSValueXor},
#line 312 "CSSValueKeywords.gperf"
      {"clip", CSSValueClip},
#line 368 "CSSValueKeywords.gperf"
      {"visual", CSSValueVisual},
#line 301 "CSSValueKeywords.gperf"
      {"fast", CSSValueFast},
#line 147 "CSSValueKeywords.gperf"
      {"super", CSSValueSuper},
#line 317 "CSSValueKeywords.gperf"
      {"wave", CSSValueWave},
#line 34 "CSSValueKeywords.gperf"
      {"all", CSSValueAll},
#line 274 "CSSValueKeywords.gperf"
      {"pre-line", CSSValuePreLine},
#line 331 "CSSValueKeywords.gperf"
      {"listbox", CSSValueListbox},
#line 230 "CSSValueKeywords.gperf"
      {"wait", CSSValueWait},
#line 294 "CSSValueKeywords.gperf"
      {"multiple", CSSValueMultiple},
#line 306 "CSSValueKeywords.gperf"
      {"read-write", CSSValueReadWrite},
#line 255 "CSSValueKeywords.gperf"
      {"hand", CSSValueHand},
#line 83 "CSSValueKeywords.gperf"
      {"navy", CSSValueNavy},
#line 185 "CSSValueKeywords.gperf"
      {"list-item", CSSValueListItem},
#line 325 "CSSValueKeywords.gperf"
      {"radio", CSSValueRadio},
#line 165 "CSSValueKeywords.gperf"
      {"square", CSSValueSquare},
#line 280 "CSSValueKeywords.gperf"
      {"static", CSSValueStatic},
#line 33 "CSSValueKeywords.gperf"
      {"oblique", CSSValueOblique},
#line 24 "CSSValueKeywords.gperf"
      {"icon", CSSValueIcon},
#line 285 "CSSValueKeywords.gperf"
      {"stretch", CSSValueStretch},
#line 102 "CSSValueKeywords.gperf"
      {"buttontext", CSSValueButtontext},
#line 132 "CSSValueKeywords.gperf"
      {"copy", CSSValueCopy},
#line 12 "CSSValueKeywords.gperf"
      {"initial", CSSValueInitial},
#line 216 "CSSValueKeywords.gperf"
      {"ne-resize", CSSValueNeResize},
#line 223 "CSSValueKeywords.gperf"
      {"ew-resize", CSSValueEwResize},
#line 375 "CSSValueKeywords.gperf"
      {"linear", CSSValueLinear},
#line 211 "CSSValueKeywords.gperf"
      {"no-drop", CSSValueNoDrop},
#line 217 "CSSValueKeywords.gperf"
      {"nw-resize", CSSValueNwResize},
#line 252 "CSSValueKeywords.gperf"
      {"cross", CSSValueCross},
#line 80 "CSSValueKeywords.gperf"
      {"green", CSSValueGreen},
#line 144 "CSSValueKeywords.gperf"
      {"baseline", CSSValueBaseline},
#line 154 "CSSValueKeywords.gperf"
      {"left", CSSValueLeft},
#line 53 "CSSValueKeywords.gperf"
      {"large", CSSValueLarge},
#line 125 "CSSValueKeywords.gperf"
      {"grey", CSSValueGrey},
#line 279 "CSSValueKeywords.gperf"
      {"show", CSSValueShow},
#line 58 "CSSValueKeywords.gperf"
      {"larger", CSSValueLarger},
#line 302 "CSSValueKeywords.gperf"
      {"infinite", CSSValueInfinite},
#line 189 "CSSValueKeywords.gperf"
      {"table", CSSValueTable},
#line 300 "CSSValueKeywords.gperf"
      {"slow", CSSValueSlow},
#line 226 "CSSValueKeywords.gperf"
      {"nwse-resize", CSSValueNwseResize},
#line 105 "CSSValueKeywords.gperf"
      {"highlight", CSSValueHighlight},
#line 162 "CSSValueKeywords.gperf"
      {"inside", CSSValueInside},
#line 310 "CSSValueKeywords.gperf"
      {"intrinsic", CSSValueIntrinsic},
#line 251 "CSSValueKeywords.gperf"
      {"crop", CSSValueCrop},
#line 127 "CSSValueKeywords.gperf"
      {"repeat", CSSValueRepeat},
#line 228 "CSSValueKeywords.gperf"
      {"row-resize", CSSValueRowResize},
#line 79 "CSSValueKeywords.gperf"
      {"gray", CSSValueGray},
#line 313 "CSSValueKeywords.gperf"
      {"ellipsis", CSSValueEllipsis},
#line 227 "CSSValueKeywords.gperf"
      {"col-resize", CSSValueColResize},
#line 219 "CSSValueKeywords.gperf"
      {"se-resize", CSSValueSeResize},
#line 209 "CSSValueKeywords.gperf"
      {"alias", CSSValueAlias},
#line 36 "CSSValueKeywords.gperf"
      {"normal", CSSValueNormal},
#line 86 "CSSValueKeywords.gperf"
      {"purple", CSSValuePurple},
#line 224 "CSSValueKeywords.gperf"
      {"ns-resize", CSSValueNsResize},
#line 121 "CSSValueKeywords.gperf"
      {"windowframe", CSSValueWindowframe},
#line 220 "CSSValueKeywords.gperf"
      {"sw-resize", CSSValueSwResize},
#line 248 "CSSValueKeywords.gperf"
      {"blink", CSSValueBlink},
#line 75 "CSSValueKeywords.gperf"
      {"aqua", CSSValueAqua},
#line 201 "CSSValueKeywords.gperf"
      {"auto", CSSValueAuto},
#line 367 "CSSValueKeywords.gperf"
      {"logical", CSSValueLogical},
#line 311 "CSSValueKeywords.gperf"
      {"min-intrinsic", CSSValueMinIntrinsic},
#line 215 "CSSValueKeywords.gperf"
      {"e-resize", CSSValueEResize},
#line 351 "CSSValueKeywords.gperf"
      {"caret", CSSValueCaret},
#line 218 "CSSValueKeywords.gperf"
      {"n-resize", CSSValueNResize},
#line 242 "CSSValueKeywords.gperf"
      {"above", CSSValueAbove},
#line 222 "CSSValueKeywords.gperf"
      {"w-resize", CSSValueWResize},
#line 318 "CSSValueKeywords.gperf"
      {"continuous", CSSValueContinuous},
#line 225 "CSSValueKeywords.gperf"
      {"nesw-resize", CSSValueNeswResize},
#line 360 "CSSValueKeywords.gperf"
      {"round", CSSValueRound},
#line 376 "CSSValueKeywords.gperf"
      {"ease-in", CSSValueEaseIn},
#line 370 "CSSValueKeywords.gperf"
      {"running", CSSValueRunning},
#line 305 "CSSValueKeywords.gperf"
      {"read-only", CSSValueReadOnly},
#line 161 "CSSValueKeywords.gperf"
      {"outside", CSSValueOutside},
#line 85 "CSSValueKeywords.gperf"
      {"orange", CSSValueOrange},
#line 329 "CSSValueKeywords.gperf"
      {"button-bevel", CSSValueButtonBevel},
#line 277 "CSSValueKeywords.gperf"
      {"scroll", CSSValueScroll},
#line 243 "CSSValueKeywords.gperf"
      {"absolute", CSSValueAbsolute},
#line 106 "CSSValueKeywords.gperf"
      {"highlighttext", CSSValueHighlighttext},
#line 210 "CSSValueKeywords.gperf"
      {"progress", CSSValueProgress},
#line 253 "CSSValueKeywords.gperf"
      {"embed", CSSValueEmbed},
#line 290 "CSSValueKeywords.gperf"
      {"vertical", CSSValueVertical},
#line 289 "CSSValueKeywords.gperf"
      {"horizontal", CSSValueHorizontal},
#line 60 "CSSValueKeywords.gperf"
      {"narrower", CSSValueNarrower},
#line 345 "CSSValueKeywords.gperf"
      {"menulist-text", CSSValueMenulistText},
#line 104 "CSSValueKeywords.gperf"
      {"graytext", CSSValueGraytext},
#line 377 "CSSValueKeywords.gperf"
      {"ease-out", CSSValueEaseOut},
#line 309 "CSSValueKeywords.gperf"
      {"ignore", CSSValueIgnore},
#line 326 "CSSValueKeywords.gperf"
      {"push-button", CSSValuePushButton},
#line 22 "CSSValueKeywords.gperf"
      {"double", CSSValueDouble},
#line 254 "CSSValueKeywords.gperf"
      {"fixed", CSSValueFixed},
#line 176 "CSSValueKeywords.gperf"
      {"armenian", CSSValueArmenian},
#line 278 "CSSValueKeywords.gperf"
      {"separate", CSSValueSeparate},
#line 21 "CSSValueKeywords.gperf"
      {"solid", CSSValueSolid},
#line 221 "CSSValueKeywords.gperf"
      {"s-resize", CSSValueSResize},
#line 149 "CSSValueKeywords.gperf"
      {"text-bottom", CSSValueTextBottom},
#line 304 "CSSValueKeywords.gperf"
      {"alternate", CSSValueAlternate},
#line 148 "CSSValueKeywords.gperf"
      {"text-top", CSSValueTextTop},
#line 344 "CSSValueKeywords.gperf"
      {"menulist-button", CSSValueMenulistButton},
#line 383 "CSSValueKeywords.gperf"
      {"visiblestroke", CSSValueVisiblestroke},
#line 270 "CSSValueKeywords.gperf"
      {"overlay", CSSValueOverlay},
#line 99 "CSSValueKeywords.gperf"
      {"buttonface", CSSValueButtonface},
#line 124 "CSSValueKeywords.gperf"
      {"currentcolor", CSSValueCurrentcolor},
#line 357 "CSSValueKeywords.gperf"
      {"textfield", CSSValueTextfield},
#line 134 "CSSValueKeywords.gperf"
      {"source-in", CSSValueSourceIn},
#line 82 "CSSValueKeywords.gperf"
      {"maroon", CSSValueMaroon},
#line 299 "CSSValueKeywords.gperf"
      {"down", CSSValueDown},
#line 190 "CSSValueKeywords.gperf"
      {"inline-table", CSSValueInlineTable},
#line 272 "CSSValueKeywords.gperf"
      {"portrait", CSSValuePortrait},
#line 23 "CSSValueKeywords.gperf"
      {"caption", CSSValueCaption},
#line 164 "CSSValueKeywords.gperf"
      {"circle", CSSValueCircle},
#line 50 "CSSValueKeywords.gperf"
      {"x-small", CSSValueXSmall},
#line 111 "CSSValueKeywords.gperf"
      {"infotext", CSSValueInfotext},
#line 133 "CSSValueKeywords.gperf"
      {"source-over", CSSValueSourceOver},
#line 208 "CSSValueKeywords.gperf"
      {"context-menu", CSSValueContextMenu},
#line 16 "CSSValueKeywords.gperf"
      {"groove", CSSValueGroove},
#line 202 "CSSValueKeywords.gperf"
      {"crosshair", CSSValueCrosshair},
#line 92 "CSSValueKeywords.gperf"
      {"transparent", CSSValueTransparent},
#line 49 "CSSValueKeywords.gperf"
      {"xx-small", CSSValueXxSmall},
#line 130 "CSSValueKeywords.gperf"
      {"no-repeat", CSSValueNoRepeat},
#line 135 "CSSValueKeywords.gperf"
      {"source-out", CSSValueSourceOut},
#line 194 "CSSValueKeywords.gperf"
      {"table-row", CSSValueTableRow},
#line 365 "CSSValueKeywords.gperf"
      {"border-box", CSSValueBorderBox},
#line 386 "CSSValueKeywords.gperf"
      {"stroke", CSSValueStroke},
#line 187 "CSSValueKeywords.gperf"
      {"compact", CSSValueCompact},
#line 239 "CSSValueKeywords.gperf"
      {"lowercase", CSSValueLowercase},
#line 327 "CSSValueKeywords.gperf"
      {"square-button", CSSValueSquareButton},
#line 358 "CSSValueKeywords.gperf"
      {"textarea", CSSValueTextarea},
#line 275 "CSSValueKeywords.gperf"
      {"pre-wrap", CSSValuePreWrap},
#line 112 "CSSValueKeywords.gperf"
      {"match", CSSValueMatch},
#line 268 "CSSValueKeywords.gperf"
      {"nowrap", CSSValueNowrap},
#line 322 "CSSValueKeywords.gperf"
      {"space", CSSValueSpace},
#line 232 "CSSValueKeywords.gperf"
      {"all-scroll", CSSValueAllScroll},
#line 366 "CSSValueKeywords.gperf"
      {"content-box", CSSValueContentBox},
#line 281 "CSSValueKeywords.gperf"
      {"thick", CSSValueThick},
#line 244 "CSSValueKeywords.gperf"
      {"always", CSSValueAlways},
#line 63 "CSSValueKeywords.gperf"
      {"condensed", CSSValueCondensed},
#line 269 "CSSValueKeywords.gperf"
      {"open-quote", CSSValueOpenQuote},
#line 297 "CSSValueKeywords.gperf"
      {"ahead", CSSValueAhead},
#line 250 "CSSValueKeywords.gperf"
      {"close-quote", CSSValueCloseQuote},
#line 172 "CSSValueKeywords.gperf"
      {"lower-latin", CSSValueLowerLatin},
#line 261 "CSSValueKeywords.gperf"
      {"line-through", CSSValueLineThrough},
#line 241 "CSSValueKeywords.gperf"
      {"collapse", CSSValueCollapse},
#line 103 "CSSValueKeywords.gperf"
      {"captiontext", CSSValueCaptiontext},
#line 128 "CSSValueKeywords.gperf"
      {"repeat-x", CSSValueRepeatX},
#line 197 "CSSValueKeywords.gperf"
      {"table-cell", CSSValueTableCell},
#line 348 "CSSValueKeywords.gperf"
      {"slider-vertical", CSSValueSliderVertical},
#line 247 "CSSValueKeywords.gperf"
      {"bidi-override", CSSValueBidiOverride},
#line 143 "CSSValueKeywords.gperf"
      {"plus-lighter", CSSValuePlusLighter},
#line 54 "CSSValueKeywords.gperf"
      {"x-large", CSSValueXLarge},
#line 70 "CSSValueKeywords.gperf"
      {"sans-serif", CSSValueSansSerif},
#line 363 "CSSValueKeywords.gperf"
      {"padding", CSSValuePadding},
#line 373 "CSSValueKeywords.gperf"
      {"preserve-3d", CSSValuePreserve3d},
#line 129 "CSSValueKeywords.gperf"
      {"repeat-y", CSSValueRepeatY},
#line 163 "CSSValueKeywords.gperf"
      {"disc", CSSValueDisc},
#line 291 "CSSValueKeywords.gperf"
      {"inline-axis", CSSValueInlineAxis},
#line 168 "CSSValueKeywords.gperf"
      {"lower-roman", CSSValueLowerRoman},
#line 378 "CSSValueKeywords.gperf"
      {"ease-in-out", CSSValueEaseInOut},
#line 371 "CSSValueKeywords.gperf"
      {"paused", CSSValuePaused},
#line 347 "CSSValueKeywords.gperf"
      {"slider-horizontal", CSSValueSliderHorizontal},
#line 245 "CSSValueKeywords.gperf"
      {"avoid", CSSValueAvoid},
#line 78 "CSSValueKeywords.gperf"
      {"fuchsia", CSSValueFuchsia},
#line 352 "CSSValueKeywords.gperf"
      {"searchfield", CSSValueSearchfield},
#line 238 "CSSValueKeywords.gperf"
      {"uppercase", CSSValueUppercase},
#line 203 "CSSValueKeywords.gperf"
      {"default", CSSValueDefault},
#line 114 "CSSValueKeywords.gperf"
      {"scrollbar", CSSValueScrollbar},
#line 237 "CSSValueKeywords.gperf"
      {"capitalize", CSSValueCapitalize},
#line 188 "CSSValueKeywords.gperf"
      {"inline-block", CSSValueInlineBlock},
#line 76 "CSSValueKeywords.gperf"
      {"black", CSSValueBlack},
#line 384 "CSSValueKeywords.gperf"
      {"painted", CSSValuePainted},
#line 196 "CSSValueKeywords.gperf"
      {"table-column", CSSValueTableColumn},
#line 174 "CSSValueKeywords.gperf"
      {"upper-latin", CSSValueUpperLatin},
#line 379 "CSSValueKeywords.gperf"
      {"document", CSSValueDocument},
#line 72 "CSSValueKeywords.gperf"
      {"fantasy", CSSValueFantasy},
#line 31 "CSSValueKeywords.gperf"
      {"status-bar", CSSValueStatusBar},
#line 206 "CSSValueKeywords.gperf"
      {"vertical-text", CSSValueVerticalText},
#line 19 "CSSValueKeywords.gperf"
      {"dotted", CSSValueDotted},
#line 350 "CSSValueKeywords.gperf"
      {"sliderthumb-vertical", CSSValueSliderthumbVertical},
#line 116 "CSSValueKeywords.gperf"
      {"threedface", CSSValueThreedface},
#line 267 "CSSValueKeywords.gperf"
      {"no-open-quote", CSSValueNoOpenQuote},
#line 169 "CSSValueKeywords.gperf"
      {"upper-roman", CSSValueUpperRoman},
#line 95 "CSSValueKeywords.gperf"
      {"activeborder", CSSValueActiveborder},
#line 73 "CSSValueKeywords.gperf"
      {"monospace", CSSValueMonospace},
#line 158 "CSSValueKeywords.gperf"
      {"-webkit-left", CSSValueWebkitLeft},
#line 349 "CSSValueKeywords.gperf"
      {"sliderthumb-horizontal", CSSValueSliderthumbHorizontal},
#line 334 "CSSValueKeywords.gperf"
      {"media-mute-button", CSSValueMediaMuteButton},
#line 381 "CSSValueKeywords.gperf"
      {"visiblepainted", CSSValueVisiblepainted},
#line 212 "CSSValueKeywords.gperf"
      {"not-allowed", CSSValueNotAllowed},
#line 184 "CSSValueKeywords.gperf"
      {"block", CSSValueBlock},
#line 100 "CSSValueKeywords.gperf"
      {"buttonhighlight", CSSValueButtonhighlight},
#line 55 "CSSValueKeywords.gperf"
      {"xx-large", CSSValueXxLarge},
#line 259 "CSSValueKeywords.gperf"
      {"landscape", CSSValueLandscape},
#line 320 "CSSValueKeywords.gperf"
      {"break-all", CSSValueBreakAll},
#line 346 "CSSValueKeywords.gperf"
      {"menulist-textfield", CSSValueMenulistTextfield},
#line 107 "CSSValueKeywords.gperf"
      {"inactiveborder", CSSValueInactiveborder},
#line 138 "CSSValueKeywords.gperf"
      {"destination-in", CSSValueDestinationIn},
#line 96 "CSSValueKeywords.gperf"
      {"activecaption", CSSValueActivecaption},
#line 126 "CSSValueKeywords.gperf"
      {"-webkit-text", CSSValueWebkitText},
#line 160 "CSSValueKeywords.gperf"
      {"-webkit-center", CSSValueWebkitCenter},
#line 338 "CSSValueKeywords.gperf"
      {"media-slider", CSSValueMediaSlider},
#line 20 "CSSValueKeywords.gperf"
      {"dashed", CSSValueDashed},
#line 101 "CSSValueKeywords.gperf"
      {"buttonshadow", CSSValueButtonshadow},
#line 137 "CSSValueKeywords.gperf"
      {"destination-over", CSSValueDestinationOver},
#line 179 "CSSValueKeywords.gperf"
      {"hiragana", CSSValueHiragana},
#line 295 "CSSValueKeywords.gperf"
      {"forwards", CSSValueForwards},
#line 136 "CSSValueKeywords.gperf"
      {"source-atop", CSSValueSourceAtop},
#line 27 "CSSValueKeywords.gperf"
      {"small-caption", CSSValueSmallCaption},
#line 139 "CSSValueKeywords.gperf"
      {"destination-out", CSSValueDestinationOut},
#line 26 "CSSValueKeywords.gperf"
      {"message-box", CSSValueMessageBox},
#line 324 "CSSValueKeywords.gperf"
      {"checkbox", CSSValueCheckbox},
#line 166 "CSSValueKeywords.gperf"
      {"decimal", CSSValueDecimal},
#line 170 "CSSValueKeywords.gperf"
      {"lower-greek", CSSValueLowerGreek},
#line 35 "CSSValueKeywords.gperf"
      {"small-caps", CSSValueSmallCaps},
#line 108 "CSSValueKeywords.gperf"
      {"inactivecaption", CSSValueInactivecaption},
#line 66 "CSSValueKeywords.gperf"
      {"expanded", CSSValueExpanded},
#line 171 "CSSValueKeywords.gperf"
      {"lower-alpha", CSSValueLowerAlpha},
#line 199 "CSSValueKeywords.gperf"
      {"-webkit-box", CSSValueWebkitBox},
#line 321 "CSSValueKeywords.gperf"
      {"break-word", CSSValueBreakWord},
#line 30 "CSSValueKeywords.gperf"
      {"-webkit-control", CSSValueWebkitControl},
#line 266 "CSSValueKeywords.gperf"
      {"no-close-quote", CSSValueNoCloseQuote},
#line 339 "CSSValueKeywords.gperf"
      {"media-sliderthumb", CSSValueMediaSliderthumb},
#line 333 "CSSValueKeywords.gperf"
      {"media-fullscreen-button", CSSValueMediaFullscreenButton},
#line 330 "CSSValueKeywords.gperf"
      {"default-button", CSSValueDefaultButton},
#line 198 "CSSValueKeywords.gperf"
      {"table-caption", CSSValueTableCaption},
#line 177 "CSSValueKeywords.gperf"
      {"georgian", CSSValueGeorgian},
#line 109 "CSSValueKeywords.gperf"
      {"inactivecaptiontext", CSSValueInactivecaptiontext},
#line 364 "CSSValueKeywords.gperf"
      {"padding-box", CSSValuePaddingBox},
#line 117 "CSSValueKeywords.gperf"
      {"threedhighlight", CSSValueThreedhighlight},
#line 153 "CSSValueKeywords.gperf"
      {"-webkit-auto", CSSValueWebkitAuto},
#line 159 "CSSValueKeywords.gperf"
      {"-webkit-right", CSSValueWebkitRight},
#line 173 "CSSValueKeywords.gperf"
      {"upper-alpha", CSSValueUpperAlpha},
#line 93 "CSSValueKeywords.gperf"
      {"-webkit-link", CSSValueWebkitLink},
#line 340 "CSSValueKeywords.gperf"
      {"media-timeline-container", CSSValueMediaTimelineContainer},
#line 213 "CSSValueKeywords.gperf"
      {"-webkit-zoom-in", CSSValueWebkitZoomIn},
#line 315 "CSSValueKeywords.gperf"
      {"dot-dash", CSSValueDotDash},
#line 119 "CSSValueKeywords.gperf"
      {"threedshadow", CSSValueThreedshadow},
#line 142 "CSSValueKeywords.gperf"
      {"plus-darker", CSSValuePlusDarker},
#line 214 "CSSValueKeywords.gperf"
      {"-webkit-zoom-out", CSSValueWebkitZoomOut},
#line 264 "CSSValueKeywords.gperf"
      {"-webkit-marquee", CSSValueWebkitMarquee},
#line 64 "CSSValueKeywords.gperf"
      {"semi-condensed", CSSValueSemiCondensed},
#line 284 "CSSValueKeywords.gperf"
      {"-webkit-nowrap", CSSValueWebkitNowrap},
#line 323 "CSSValueKeywords.gperf"
      {"after-white-space", CSSValueAfterWhiteSpace},
#line 200 "CSSValueKeywords.gperf"
      {"-webkit-inline-box", CSSValueWebkitInlineBox},
#line 314 "CSSValueKeywords.gperf"
      {"discard", CSSValueDiscard},
#line 28 "CSSValueKeywords.gperf"
      {"-webkit-mini-control", CSSValueWebkitMiniControl},
#line 335 "CSSValueKeywords.gperf"
      {"media-play-button", CSSValueMediaPlayButton},
#line 140 "CSSValueKeywords.gperf"
      {"destination-atop", CSSValueDestinationAtop},
#line 191 "CSSValueKeywords.gperf"
      {"table-row-group", CSSValueTableRowGroup},
#line 296 "CSSValueKeywords.gperf"
      {"backwards", CSSValueBackwards},
#line 180 "CSSValueKeywords.gperf"
      {"katakana", CSSValueKatakana},
#line 193 "CSSValueKeywords.gperf"
      {"table-footer-group", CSSValueTableFooterGroup},
#line 307 "CSSValueKeywords.gperf"
      {"read-write-plaintext-only", CSSValueReadWritePlaintextOnly},
#line 98 "CSSValueKeywords.gperf"
      {"background", CSSValueBackground},
#line 74 "CSSValueKeywords.gperf"
      {"-webkit-body", CSSValueWebkitBody},
#line 233 "CSSValueKeywords.gperf"
      {"-webkit-grab", CSSValueWebkitGrab},
#line 178 "CSSValueKeywords.gperf"
      {"cjk-ideographic", CSSValueCjkIdeographic},
#line 181 "CSSValueKeywords.gperf"
      {"hiragana-iroha", CSSValueHiraganaIroha},
#line 65 "CSSValueKeywords.gperf"
      {"semi-expanded", CSSValueSemiExpanded},
#line 94 "CSSValueKeywords.gperf"
      {"-webkit-activelink", CSSValueWebkitActivelink},
#line 195 "CSSValueKeywords.gperf"
      {"table-column-group", CSSValueTableColumnGroup},
#line 292 "CSSValueKeywords.gperf"
      {"block-axis", CSSValueBlockAxis},
#line 319 "CSSValueKeywords.gperf"
      {"skip-white-space", CSSValueSkipWhiteSpace},
#line 355 "CSSValueKeywords.gperf"
      {"searchfield-results-button", CSSValueSearchfieldResultsButton},
#line 97 "CSSValueKeywords.gperf"
      {"appworkspace", CSSValueAppworkspace},
#line 118 "CSSValueKeywords.gperf"
      {"threedlightshadow", CSSValueThreedlightshadow},
#line 61 "CSSValueKeywords.gperf"
      {"ultra-condensed", CSSValueUltraCondensed},
#line 62 "CSSValueKeywords.gperf"
      {"extra-condensed", CSSValueExtraCondensed},
#line 29 "CSSValueKeywords.gperf"
      {"-webkit-small-control", CSSValueWebkitSmallControl},
#line 356 "CSSValueKeywords.gperf"
      {"searchfield-cancel-button", CSSValueSearchfieldCancelButton},
#line 353 "CSSValueKeywords.gperf"
      {"searchfield-decoration", CSSValueSearchfieldDecoration},
#line 316 "CSSValueKeywords.gperf"
      {"dot-dot-dash", CSSValueDotDotDash},
#line 68 "CSSValueKeywords.gperf"
      {"ultra-expanded", CSSValueUltraExpanded},
#line 234 "CSSValueKeywords.gperf"
      {"-webkit-grabbing", CSSValueWebkitGrabbing},
#line 67 "CSSValueKeywords.gperf"
      {"extra-expanded", CSSValueExtraExpanded},
#line 192 "CSSValueKeywords.gperf"
      {"table-header-group", CSSValueTableHeaderGroup},
#line 182 "CSSValueKeywords.gperf"
      {"katakana-iroha", CSSValueKatakanaIroha},
#line 56 "CSSValueKeywords.gperf"
      {"-webkit-xxx-large", CSSValueWebkitXxxLarge},
#line 110 "CSSValueKeywords.gperf"
      {"infobackground", CSSValueInfobackground},
#line 341 "CSSValueKeywords.gperf"
      {"media-current-time-display", CSSValueMediaCurrentTimeDisplay},
#line 123 "CSSValueKeywords.gperf"
      {"-webkit-focus-ring-color", CSSValueWebkitFocusRingColor},
#line 337 "CSSValueKeywords.gperf"
      {"media-seek-forward-button", CSSValueMediaSeekForwardButton},
#line 336 "CSSValueKeywords.gperf"
      {"media-seek-back-button", CSSValueMediaSeekBackButton},
#line 359 "CSSValueKeywords.gperf"
      {"caps-lock-indicator", CSSValueCapsLockIndicator},
#line 115 "CSSValueKeywords.gperf"
      {"threeddarkshadow", CSSValueThreeddarkshadow},
#line 354 "CSSValueKeywords.gperf"
      {"searchfield-results-decoration", CSSValueSearchfieldResultsDecoration},
#line 152 "CSSValueKeywords.gperf"
      {"-webkit-baseline-middle", CSSValueWebkitBaselineMiddle},
#line 167 "CSSValueKeywords.gperf"
      {"decimal-leading-zero", CSSValueDecimalLeadingZero},
#line 342 "CSSValueKeywords.gperf"
      {"media-time-remaining-display", CSSValueMediaTimeRemainingDisplay}
    };

  static const short lookup[] =
    {
       -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,
        1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        2,  -1,  -1,   3,  -1,   4,  -1,  -1,   5,  -1,
        6,  -1,  -1,   7,  -1,   8,  -1,  -1,   9,  -1,
       10,  11,  -1,  -1,  -1,  12,  -1,  -1,  -1,  -1,
       13,  14,  -1,  -1,  -1,  15,  -1,  16,  17,  -1,
       18,  19,  -1,  -1,  -1,  20,  21,  -1,  -1,  -1,
       22,  23,  -1,  24,  -1,  25,  -1,  -1,  26,  -1,
       27,  -1,  -1,  -1,  -1,  28,  -1,  -1,  29,  -1,
       30,  -1,  -1,  -1,  -1,  31,  -1,  -1,  32,  33,
       34,  -1,  -1,  35,  -1,  36,  -1,  -1,  -1,  -1,
       37,  38,  -1,  -1,  -1,  39,  40,  -1,  41,  -1,
       42,  -1,  -1,  -1,  -1,  43,  -1,  -1,  -1,  -1,
       44,  -1,  -1,  45,  -1,  46,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  47,  -1,  -1,  -1,
       48,  -1,  -1,  -1,  -1,  49,  -1,  50,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  51,  -1,  -1,  -1,  -1,
       52,  53,  -1,  -1,  -1,  54,  55,  -1,  -1,  56,
       -1,  57,  -1,  -1,  -1,  58,  -1,  -1,  -1,  -1,
       -1,  59,  -1,  -1,  -1,  -1,  -1,  -1,  60,  -1,
       61,  62,  63,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       64,  65,  -1,  -1,  -1,  66,  -1,  -1,  67,  -1,
       68,  -1,  -1,  69,  -1,  -1,  -1,  -1,  70,  -1,
       71,  -1,  -1,  72,  73,  74,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  75,  76,  -1,  -1,  -1,  -1,
       77,  -1,  -1,  -1,  -1,  78,  -1,  -1,  -1,  -1,
       79,  -1,  -1,  80,  -1,  81,  82,  -1,  -1,  -1,
       83,  -1,  -1,  -1,  -1,  84,  -1,  85,  86,  -1,
       87,  -1,  -1,  88,  89,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  90,  -1,  -1,  -1,
       91,  92,  93,  -1,  -1,  94,  -1,  95,  96,  97,
       98,  99,  -1, 100, 101, 102,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 103, 104, 105,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 106, 107,  -1,  -1, 108,  -1,
       -1,  -1,  -1, 109, 110,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 111,  -1, 112,  -1,  -1,  -1,  -1,
       -1, 113,  -1,  -1,  -1, 114,  -1, 115,  -1,  -1,
       -1, 116,  -1,  -1,  -1, 117, 118,  -1,  -1,  -1,
      119, 120,  -1, 121, 122,  -1, 123,  -1, 124, 125,
       -1,  -1,  -1,  -1,  -1, 126,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 127, 128, 129,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 130,  -1, 131, 132,  -1,  -1,  -1,
       -1, 133,  -1,  -1,  -1,  -1,  -1,  -1, 134,  -1,
       -1,  -1,  -1,  -1, 135,  -1,  -1,  -1, 136,  -1,
      137,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      138,  -1,  -1, 139,  -1, 140, 141,  -1,  -1,  -1,
      142,  -1, 143,  -1,  -1,  -1, 144,  -1, 145, 146,
      147, 148, 149,  -1,  -1,  -1,  -1,  -1, 150,  -1,
       -1,  -1,  -1,  -1,  -1, 151,  -1,  -1, 152,  -1,
       -1, 153,  -1,  -1, 154, 155, 156,  -1, 157,  -1,
      158, 159,  -1,  -1,  -1,  -1, 160,  -1,  -1,  -1,
      161, 162,  -1, 163,  -1, 164,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 165,  -1,  -1, 166,  -1,
       -1,  -1,  -1, 167,  -1, 168,  -1,  -1, 169,  -1,
       -1,  -1,  -1,  -1, 170,  -1,  -1,  -1,  -1,  -1,
       -1, 171,  -1,  -1,  -1,  -1, 172, 173,  -1,  -1,
      174, 175,  -1,  -1,  -1, 176,  -1,  -1, 177,  -1,
       -1, 178,  -1,  -1,  -1, 179, 180,  -1, 181,  -1,
       -1,  -1,  -1, 182,  -1,  -1, 183,  -1,  -1,  -1,
      184, 185,  -1, 186,  -1,  -1, 187,  -1,  -1, 188,
      189,  -1,  -1,  -1,  -1, 190, 191,  -1, 192,  -1,
      193,  -1,  -1, 194,  -1,  -1,  -1,  -1, 195,  -1,
      196, 197,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      198,  -1,  -1, 199, 200,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 201,  -1, 202, 203,
       -1,  -1,  -1, 204,  -1, 205,  -1,  -1, 206,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 207, 208,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 209,  -1, 210,  -1,
       -1,  -1,  -1,  -1,  -1, 211, 212,  -1, 213, 214,
       -1, 215,  -1, 216,  -1,  -1,  -1,  -1, 217,  -1,
       -1,  -1,  -1, 218,  -1, 219,  -1, 220, 221,  -1,
       -1, 222,  -1,  -1, 223, 224, 225,  -1, 226,  -1,
       -1, 227,  -1, 228,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 229,  -1,  -1,
      230,  -1,  -1,  -1, 231,  -1,  -1,  -1,  -1, 232,
      233, 234,  -1,  -1,  -1,  -1, 235, 236,  -1, 237,
      238,  -1,  -1,  -1,  -1,  -1, 239,  -1, 240,  -1,
       -1,  -1, 241,  -1,  -1, 242, 243,  -1, 244,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      245,  -1,  -1, 246, 247,  -1,  -1,  -1,  -1,  -1,
       -1, 248,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 249,  -1,  -1, 250,  -1,
       -1, 251,  -1,  -1,  -1,  -1, 252,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      253,  -1, 254,  -1,  -1,  -1,  -1,  -1, 255,  -1,
      256,  -1,  -1, 257,  -1, 258, 259,  -1, 260,  -1,
       -1, 261,  -1,  -1,  -1, 262, 263,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 264,  -1,  -1,  -1, 265,
       -1,  -1,  -1, 266,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 267,  -1,
       -1, 268,  -1,  -1,  -1,  -1, 269,  -1,  -1,  -1,
      270, 271, 272, 273,  -1,  -1, 274,  -1, 275,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      276, 277,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 278, 279,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      280,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 281,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 282,  -1,
      283,  -1,  -1,  -1,  -1,  -1, 284,  -1,  -1, 285,
       -1, 286,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 287,  -1,  -1,  -1,  -1,  -1,  -1,
      288,  -1,  -1,  -1, 289,  -1,  -1,  -1, 290, 291,
       -1,  -1,  -1, 292,  -1,  -1,  -1,  -1, 293,  -1,
       -1,  -1,  -1,  -1,  -1, 294,  -1,  -1,  -1,  -1,
      295,  -1,  -1,  -1, 296,  -1,  -1,  -1,  -1,  -1,
       -1, 297,  -1, 298,  -1,  -1,  -1,  -1,  -1, 299,
      300,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 301,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 302,  -1,  -1,  -1,  -1,  -1,
       -1, 303,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 304,
       -1, 305,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 306,  -1,  -1,  -1,  -1,  -1,  -1, 307,  -1,
       -1, 308,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 309,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 310,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      311,  -1, 312,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 313,  -1,  -1, 314,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 315,  -1, 316,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      317,  -1,  -1,  -1, 318,  -1,  -1,  -1,  -1,  -1,
       -1, 319,  -1, 320,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 321,
       -1,  -1,  -1,  -1,  -1, 322,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 323,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 324, 325,
       -1,  -1, 326,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 327,  -1,
       -1,  -1, 328,  -1,  -1,  -1,  -1,  -1,  -1, 329,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 330,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 331, 332,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 333,
      334,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 335,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 336,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      337, 338,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      339, 340, 341,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 342,  -1,  -1,  -1,  -1,  -1,  -1, 343,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 344,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 345,  -1,  -1, 346,  -1, 347,  -1,  -1,  -1,
       -1,  -1,  -1, 348,  -1,  -1,  -1,  -1, 349,  -1,
       -1,  -1,  -1, 350,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 351,  -1, 352,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 353,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 354,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 355,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 356,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 357,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 358,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 359,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 360,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 361,  -1,  -1, 362,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 363,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 364, 365,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 366,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 367,  -1,  -1,
       -1,  -1,  -1,  -1, 368,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 369,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 370,  -1,  -1,  -1,  -1,  -1, 371,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 372,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 373,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 374,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      375
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_val (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_value[index].name;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return &wordlist_value[index];
            }
        }
    }
  return 0;
}
#line 387 "CSSValueKeywords.gperf"

static const char * const valueList[] = {
"",
"inherit", 
"initial", 
"none", 
"hidden", 
"inset", 
"groove", 
"ridge", 
"outset", 
"dotted", 
"dashed", 
"solid", 
"double", 
"caption", 
"icon", 
"menu", 
"message-box", 
"small-caption", 
"-webkit-mini-control", 
"-webkit-small-control", 
"-webkit-control", 
"status-bar", 
"italic", 
"oblique", 
"all", 
"small-caps", 
"normal", 
"bold", 
"bolder", 
"lighter", 
"100", 
"200", 
"300", 
"400", 
"500", 
"600", 
"700", 
"800", 
"900", 
"xx-small", 
"x-small", 
"small", 
"medium", 
"large", 
"x-large", 
"xx-large", 
"-webkit-xxx-large", 
"smaller", 
"larger", 
"wider", 
"narrower", 
"ultra-condensed", 
"extra-condensed", 
"condensed", 
"semi-condensed", 
"semi-expanded", 
"expanded", 
"extra-expanded", 
"ultra-expanded", 
"serif", 
"sans-serif", 
"cursive", 
"fantasy", 
"monospace", 
"-webkit-body", 
"aqua", 
"black", 
"blue", 
"fuchsia", 
"gray", 
"green", 
"lime", 
"maroon", 
"navy", 
"olive", 
"orange", 
"purple", 
"red", 
"silver", 
"teal", 
"white", 
"yellow", 
"transparent", 
"-webkit-link", 
"-webkit-activelink", 
"activeborder", 
"activecaption", 
"appworkspace", 
"background", 
"buttonface", 
"buttonhighlight", 
"buttonshadow", 
"buttontext", 
"captiontext", 
"graytext", 
"highlight", 
"highlighttext", 
"inactiveborder", 
"inactivecaption", 
"inactivecaptiontext", 
"infobackground", 
"infotext", 
"match", 
"menutext", 
"scrollbar", 
"threeddarkshadow", 
"threedface", 
"threedhighlight", 
"threedlightshadow", 
"threedshadow", 
"window", 
"windowframe", 
"windowtext", 
"-webkit-focus-ring-color", 
"currentcolor", 
"grey", 
"-webkit-text", 
"repeat", 
"repeat-x", 
"repeat-y", 
"no-repeat", 
"clear", 
"copy", 
"source-over", 
"source-in", 
"source-out", 
"source-atop", 
"destination-over", 
"destination-in", 
"destination-out", 
"destination-atop", 
"xor", 
"plus-darker", 
"plus-lighter", 
"baseline", 
"middle", 
"sub", 
"super", 
"text-top", 
"text-bottom", 
"top", 
"bottom", 
"-webkit-baseline-middle", 
"-webkit-auto", 
"left", 
"right", 
"center", 
"justify", 
"-webkit-left", 
"-webkit-right", 
"-webkit-center", 
"outside", 
"inside", 
"disc", 
"circle", 
"square", 
"decimal", 
"decimal-leading-zero", 
"lower-roman", 
"upper-roman", 
"lower-greek", 
"lower-alpha", 
"lower-latin", 
"upper-alpha", 
"upper-latin", 
"hebrew", 
"armenian", 
"georgian", 
"cjk-ideographic", 
"hiragana", 
"katakana", 
"hiragana-iroha", 
"katakana-iroha", 
"inline", 
"block", 
"list-item", 
"run-in", 
"compact", 
"inline-block", 
"table", 
"inline-table", 
"table-row-group", 
"table-header-group", 
"table-footer-group", 
"table-row", 
"table-column-group", 
"table-column", 
"table-cell", 
"table-caption", 
"-webkit-box", 
"-webkit-inline-box", 
"auto", 
"crosshair", 
"default", 
"pointer", 
"move", 
"vertical-text", 
"cell", 
"context-menu", 
"alias", 
"progress", 
"no-drop", 
"not-allowed", 
"-webkit-zoom-in", 
"-webkit-zoom-out", 
"e-resize", 
"ne-resize", 
"nw-resize", 
"n-resize", 
"se-resize", 
"sw-resize", 
"s-resize", 
"w-resize", 
"ew-resize", 
"ns-resize", 
"nesw-resize", 
"nwse-resize", 
"col-resize", 
"row-resize", 
"text", 
"wait", 
"help", 
"all-scroll", 
"-webkit-grab", 
"-webkit-grabbing", 
"ltr", 
"rtl", 
"capitalize", 
"uppercase", 
"lowercase", 
"visible", 
"collapse", 
"above", 
"absolute", 
"always", 
"avoid", 
"below", 
"bidi-override", 
"blink", 
"both", 
"close-quote", 
"crop", 
"cross", 
"embed", 
"fixed", 
"hand", 
"hide", 
"higher", 
"invert", 
"landscape", 
"level", 
"line-through", 
"loud", 
"lower", 
"-webkit-marquee", 
"mix", 
"no-close-quote", 
"no-open-quote", 
"nowrap", 
"open-quote", 
"overlay", 
"overline", 
"portrait", 
"pre", 
"pre-line", 
"pre-wrap", 
"relative", 
"scroll", 
"separate", 
"show", 
"static", 
"thick", 
"thin", 
"underline", 
"-webkit-nowrap", 
"stretch", 
"start", 
"end", 
"reverse", 
"horizontal", 
"vertical", 
"inline-axis", 
"block-axis", 
"single", 
"multiple", 
"forwards", 
"backwards", 
"ahead", 
"up", 
"down", 
"slow", 
"fast", 
"infinite", 
"slide", 
"alternate", 
"read-only", 
"read-write", 
"read-write-plaintext-only", 
"element", 
"ignore", 
"intrinsic", 
"min-intrinsic", 
"clip", 
"ellipsis", 
"discard", 
"dot-dash", 
"dot-dot-dash", 
"wave", 
"continuous", 
"skip-white-space", 
"break-all", 
"break-word", 
"space", 
"after-white-space", 
"checkbox", 
"radio", 
"push-button", 
"square-button", 
"button", 
"button-bevel", 
"default-button", 
"listbox", 
"listitem", 
"media-fullscreen-button", 
"media-mute-button", 
"media-play-button", 
"media-seek-back-button", 
"media-seek-forward-button", 
"media-slider", 
"media-sliderthumb", 
"media-timeline-container", 
"media-current-time-display", 
"media-time-remaining-display", 
"menulist", 
"menulist-button", 
"menulist-text", 
"menulist-textfield", 
"slider-horizontal", 
"slider-vertical", 
"sliderthumb-horizontal", 
"sliderthumb-vertical", 
"caret", 
"searchfield", 
"searchfield-decoration", 
"searchfield-results-decoration", 
"searchfield-results-button", 
"searchfield-cancel-button", 
"textfield", 
"textarea", 
"caps-lock-indicator", 
"round", 
"border", 
"content", 
"padding", 
"padding-box", 
"border-box", 
"content-box", 
"logical", 
"visual", 
"lines", 
"running", 
"paused", 
"flat", 
"preserve-3d", 
"ease", 
"linear", 
"ease-in", 
"ease-out", 
"ease-in-out", 
"document", 
"reset", 
"visiblepainted", 
"visiblefill", 
"visiblestroke", 
"painted", 
"fill", 
"stroke", 
    0
};
const char* getValueName(unsigned short id)
{
    if (id >= numCSSValueKeywords || id <= 0)
        return 0;
    return valueList[id];
}
