/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#include "JSCSSUnknownRule.h"

#include <wtf/GetPtr.h>

#include "CSSUnknownRule.h"


using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSCSSUnknownRule);

/* Hash table for prototype */

static const HashTableValue JSCSSUnknownRulePrototypeTableValues[1] =
{
    { 0, 0, 0, 0 }
};

static const HashTable JSCSSUnknownRulePrototypeTable =
#if ENABLE(PERFECT_HASH_SIZE)
    { 0, JSCSSUnknownRulePrototypeTableValues, 0 };
#else
    { 1, 0, JSCSSUnknownRulePrototypeTableValues, 0 };
#endif

const ClassInfo JSCSSUnknownRulePrototype::s_info = { "CSSUnknownRulePrototype", 0, &JSCSSUnknownRulePrototypeTable, 0 };

JSObject* JSCSSUnknownRulePrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSCSSUnknownRule>(exec, globalObject);
}

const ClassInfo JSCSSUnknownRule::s_info = { "CSSUnknownRule", &JSCSSRule::s_info, 0, 0 };

JSCSSUnknownRule::JSCSSUnknownRule(PassRefPtr<Structure> structure, PassRefPtr<CSSUnknownRule> impl)
    : JSCSSRule(structure, impl)
{
}

JSObject* JSCSSUnknownRule::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return new (exec) JSCSSUnknownRulePrototype(JSCSSUnknownRulePrototype::createStructure(JSCSSRulePrototype::self(exec, globalObject)));
}


}
