/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "SVGElement.h"
#include "JSSVGFilterPrimitiveStandardAttributes.h"

#include <wtf/GetPtr.h>

#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedString.h"
#include "SVGFilterPrimitiveStandardAttributes.h"


using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSSVGFilterPrimitiveStandardAttributes);

/* Hash table */

static const HashTableValue JSSVGFilterPrimitiveStandardAttributesTableValues[6] =
{
    { "x", DontDelete|ReadOnly, (intptr_t)jsSVGFilterPrimitiveStandardAttributesX, (intptr_t)0 },
    { "y", DontDelete|ReadOnly, (intptr_t)jsSVGFilterPrimitiveStandardAttributesY, (intptr_t)0 },
    { "width", DontDelete|ReadOnly, (intptr_t)jsSVGFilterPrimitiveStandardAttributesWidth, (intptr_t)0 },
    { "height", DontDelete|ReadOnly, (intptr_t)jsSVGFilterPrimitiveStandardAttributesHeight, (intptr_t)0 },
    { "result", DontDelete|ReadOnly, (intptr_t)jsSVGFilterPrimitiveStandardAttributesResult, (intptr_t)0 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFilterPrimitiveStandardAttributesTable =
#if ENABLE(PERFECT_HASH_SIZE)
    { 15, JSSVGFilterPrimitiveStandardAttributesTableValues, 0 };
#else
    { 16, 15, JSSVGFilterPrimitiveStandardAttributesTableValues, 0 };
#endif

/* Hash table for prototype */

static const HashTableValue JSSVGFilterPrimitiveStandardAttributesPrototypeTableValues[1] =
{
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFilterPrimitiveStandardAttributesPrototypeTable =
#if ENABLE(PERFECT_HASH_SIZE)
    { 0, JSSVGFilterPrimitiveStandardAttributesPrototypeTableValues, 0 };
#else
    { 1, 0, JSSVGFilterPrimitiveStandardAttributesPrototypeTableValues, 0 };
#endif

const ClassInfo JSSVGFilterPrimitiveStandardAttributesPrototype::s_info = { "SVGFilterPrimitiveStandardAttributesPrototype", 0, &JSSVGFilterPrimitiveStandardAttributesPrototypeTable, 0 };

JSObject* JSSVGFilterPrimitiveStandardAttributesPrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSSVGFilterPrimitiveStandardAttributes>(exec, globalObject);
}

const ClassInfo JSSVGFilterPrimitiveStandardAttributes::s_info = { "SVGFilterPrimitiveStandardAttributes", &JSSVGStylable::s_info, &JSSVGFilterPrimitiveStandardAttributesTable, 0 };

JSSVGFilterPrimitiveStandardAttributes::JSSVGFilterPrimitiveStandardAttributes(PassRefPtr<Structure> structure, PassRefPtr<SVGFilterPrimitiveStandardAttributes> impl, SVGElement* context)
    : JSSVGStylable(structure, impl, context)
{
}

JSObject* JSSVGFilterPrimitiveStandardAttributes::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return new (exec) JSSVGFilterPrimitiveStandardAttributesPrototype(JSSVGFilterPrimitiveStandardAttributesPrototype::createStructure(JSSVGStylablePrototype::self(exec, globalObject)));
}

bool JSSVGFilterPrimitiveStandardAttributes::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFilterPrimitiveStandardAttributes, Base>(exec, &JSSVGFilterPrimitiveStandardAttributesTable, this, propertyName, slot);
}

JSValue jsSVGFilterPrimitiveStandardAttributesX(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGFilterPrimitiveStandardAttributes* imp = static_cast<SVGFilterPrimitiveStandardAttributes*>(static_cast<JSSVGFilterPrimitiveStandardAttributes*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
    return toJS(exec, obj.get(), imp);
}

JSValue jsSVGFilterPrimitiveStandardAttributesY(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGFilterPrimitiveStandardAttributes* imp = static_cast<SVGFilterPrimitiveStandardAttributes*>(static_cast<JSSVGFilterPrimitiveStandardAttributes*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
    return toJS(exec, obj.get(), imp);
}

JSValue jsSVGFilterPrimitiveStandardAttributesWidth(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGFilterPrimitiveStandardAttributes* imp = static_cast<SVGFilterPrimitiveStandardAttributes*>(static_cast<JSSVGFilterPrimitiveStandardAttributes*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
    return toJS(exec, obj.get(), imp);
}

JSValue jsSVGFilterPrimitiveStandardAttributesHeight(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGFilterPrimitiveStandardAttributes* imp = static_cast<SVGFilterPrimitiveStandardAttributes*>(static_cast<JSSVGFilterPrimitiveStandardAttributes*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
    return toJS(exec, obj.get(), imp);
}

JSValue jsSVGFilterPrimitiveStandardAttributesResult(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGFilterPrimitiveStandardAttributes* imp = static_cast<SVGFilterPrimitiveStandardAttributes*>(static_cast<JSSVGFilterPrimitiveStandardAttributes*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
    return toJS(exec, obj.get(), imp);
}


}

#endif // ENABLE(SVG)
