/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG)

#include "SVGElement.h"
#include "JSSVGExternalResourcesRequired.h"

#include <wtf/GetPtr.h>

#include "JSSVGAnimatedBoolean.h"
#include "SVGExternalResourcesRequired.h"


using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSSVGExternalResourcesRequired);

/* Hash table */

static const HashTableValue JSSVGExternalResourcesRequiredTableValues[2] =
{
    { "externalResourcesRequired", DontDelete|ReadOnly, (intptr_t)jsSVGExternalResourcesRequiredExternalResourcesRequired, (intptr_t)0 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGExternalResourcesRequiredTable =
#if ENABLE(PERFECT_HASH_SIZE)
    { 0, JSSVGExternalResourcesRequiredTableValues, 0 };
#else
    { 2, 1, JSSVGExternalResourcesRequiredTableValues, 0 };
#endif

/* Hash table for prototype */

static const HashTableValue JSSVGExternalResourcesRequiredPrototypeTableValues[1] =
{
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGExternalResourcesRequiredPrototypeTable =
#if ENABLE(PERFECT_HASH_SIZE)
    { 0, JSSVGExternalResourcesRequiredPrototypeTableValues, 0 };
#else
    { 1, 0, JSSVGExternalResourcesRequiredPrototypeTableValues, 0 };
#endif

const ClassInfo JSSVGExternalResourcesRequiredPrototype::s_info = { "SVGExternalResourcesRequiredPrototype", 0, &JSSVGExternalResourcesRequiredPrototypeTable, 0 };

JSObject* JSSVGExternalResourcesRequiredPrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSSVGExternalResourcesRequired>(exec, globalObject);
}

const ClassInfo JSSVGExternalResourcesRequired::s_info = { "SVGExternalResourcesRequired", 0, &JSSVGExternalResourcesRequiredTable, 0 };

JSSVGExternalResourcesRequired::JSSVGExternalResourcesRequired(PassRefPtr<Structure> structure, PassRefPtr<SVGExternalResourcesRequired> impl, SVGElement* context)
    : DOMObject(structure)
    , m_context(context)
    , m_impl(impl)
{
}

JSSVGExternalResourcesRequired::~JSSVGExternalResourcesRequired()
{
    forgetDOMObject(*Heap::heap(this)->globalData(), m_impl.get());
}

JSObject* JSSVGExternalResourcesRequired::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return new (exec) JSSVGExternalResourcesRequiredPrototype(JSSVGExternalResourcesRequiredPrototype::createStructure(globalObject->objectPrototype()));
}

bool JSSVGExternalResourcesRequired::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGExternalResourcesRequired, Base>(exec, &JSSVGExternalResourcesRequiredTable, this, propertyName, slot);
}

JSValue jsSVGExternalResourcesRequiredExternalResourcesRequired(ExecState* exec, const Identifier&, const PropertySlot& slot)
{
    UNUSED_PARAM(exec);
    SVGExternalResourcesRequired* imp = static_cast<SVGExternalResourcesRequired*>(static_cast<JSSVGExternalResourcesRequired*>(asObject(slot.slotBase()))->impl());
    RefPtr<SVGAnimatedBoolean> obj = imp->externalResourcesRequiredAnimated();
    return toJS(exec, obj.get(), imp);
}

JSC::JSValue toJS(JSC::ExecState* exec, SVGExternalResourcesRequired* object, SVGElement* context)
{
    return getDOMObjectWrapper<JSSVGExternalResourcesRequired>(exec, object, context);
}
SVGExternalResourcesRequired* toSVGExternalResourcesRequired(JSC::JSValue value)
{
    return value.isObject(&JSSVGExternalResourcesRequired::s_info) ? static_cast<JSSVGExternalResourcesRequired*>(asObject(value))->impl() : 0;
}

}

#endif // ENABLE(SVG)
