#!/bin/sh

# Copyright (C) 2007, 2010 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# Sets up the execution environment needed to run the test programs
# and produce the documentation.


GUILE_LOAD_PATH="/home/tjw/tjKindle/LIB2/gnutls-2.10.0/guile/modules:$GUILE_LOAD_PATH"
export GUILE_LOAD_PATH

exec /home/tjw/tjKindle/LIB2/gnutls-2.10.0/libtool --mode=execute		                    \
       -dlopen "/home/tjw/tjKindle/LIB2/gnutls-2.10.0/guile/src/libguile-gnutls-v-1.la"        \
       -dlopen "/home/tjw/tjKindle/LIB2/gnutls-2.10.0/guile/src/libguile-gnutls-extra-v-1.la"  \
        "$@"
